-- =============================================================================
-- SISTEMA DE GESTIÓN DE CONCESIONARIO (POSTGRESQL)
-- PostgreSQL
-- Autor: Efrén Sánchez / Optimización de datos: IA
-- =============================================================================

-- 1. LIMPIEZA E INICIALIZACIÓN
-- -----------------------------------------------------------------------------
DROP TABLE IF EXISTS revisiones CASCADE;
DROP TABLE IF EXISTS ventas CASCADE;
DROP TABLE IF EXISTS coches CASCADE;
DROP TABLE IF EXISTS modelos CASCADE;
DROP TABLE IF EXISTS marcas CASCADE;
DROP TABLE IF EXISTS vendedores CASCADE;
DROP TABLE IF EXISTS clientes CASCADE;

-- Borrado de tipos ENUM si ya existen
DROP TYPE IF EXISTS tipo_segmento;
DROP TYPE IF EXISTS tipo_estado;
DROP TYPE IF EXISTS tipo_vehiculo;
DROP TYPE IF EXISTS tipo_pago;

-- 2. DEFINICIÓN DE TIPOS ENUM (Personalizados en Postgres)
-- -----------------------------------------------------------------------------
CREATE TYPE tipo_segmento AS ENUM ('SUV', 'Sedán', 'Compacto', 'Deportivo', 'Pick-up', 'Eléctrico');
CREATE TYPE tipo_estado AS ENUM ('Disponible', 'Reservado', 'Vendido', 'Mantenimiento');
CREATE TYPE tipo_vehiculo AS ENUM ('Nuevo', 'Ocasión');
CREATE TYPE tipo_pago AS ENUM ('Contado', 'Financiado', 'Leasing');

-- 3. DEFINICIÓN DEL ESQUEMA (DDL)
-- -----------------------------------------------------------------------------

CREATE TABLE marcas (
    id_marca INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    pais_origen VARCHAR(50)
);

CREATE TABLE modelos (
    id_modelo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_marca INTEGER NOT NULL,
    nombre VARCHAR(50) NOT NULL,
    segmento tipo_segmento NOT NULL,
    CONSTRAINT fk_modelo_marca FOREIGN KEY (id_marca) REFERENCES marcas(id_marca)
);

CREATE TABLE coches (
    id_coche INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_modelo INTEGER NOT NULL,
    vin VARCHAR(17) UNIQUE NOT NULL,
    color VARCHAR(30),
    anio INTEGER NOT NULL,
    precio_base DECIMAL(12,2) NOT NULL,
    estado tipo_estado DEFAULT 'Disponible',
    tipo tipo_vehiculo DEFAULT 'Nuevo',
    kilometraje INTEGER DEFAULT 0,
    CONSTRAINT fk_coche_modelo FOREIGN KEY (id_modelo) REFERENCES modelos(id_modelo)
);

CREATE TABLE clientes (
    id_cliente INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    apellidos VARCHAR(100) NOT NULL,
    dni VARCHAR(15) UNIQUE NOT NULL,
    telefono VARCHAR(20),
    email VARCHAR(100),
    ciudad VARCHAR(50)
);

CREATE TABLE vendedores (
    id_vendedor INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    apellidos VARCHAR(100) NOT NULL,
    fecha_ingreso DATE NOT NULL,
    comision_pct DECIMAL(4,2) DEFAULT 1.00
);

CREATE TABLE ventas (
    id_venta INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_coche INTEGER NOT NULL,
    id_cliente INTEGER NOT NULL,
    id_vendedor INTEGER NOT NULL,
    fecha_venta TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    precio_final DECIMAL(12,2) NOT NULL,
    metodo_pago tipo_pago NOT NULL,
    CONSTRAINT fk_venta_coche FOREIGN KEY (id_coche) REFERENCES coches(id_coche),
    CONSTRAINT fk_venta_cliente FOREIGN KEY (id_cliente) REFERENCES clientes(id_cliente),
    CONSTRAINT fk_venta_vendedor FOREIGN KEY (id_vendedor) REFERENCES vendedores(id_vendedor)
);

CREATE TABLE revisiones (
    id_revision INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_coche INTEGER NOT NULL,
    fecha_revision DATE NOT NULL,
    descripcion TEXT,
    coste DECIMAL(10,2) NOT NULL,
    CONSTRAINT fk_revision_coche FOREIGN KEY (id_coche) REFERENCES coches(id_coche)
);

-- 4. CARGA DE DATOS (DML)
-- -----------------------------------------------------------------------------
BEGIN;

-- Marcas
INSERT INTO marcas (nombre, pais_origen) VALUES 
('Toyota', 'Japón'), ('BMW', 'Alemania'), ('Ford', 'USA'), 
('Tesla', 'USA'), ('Hyundai', 'Corea del Sur'), ('Audi', 'Alemania'),
('Mercedes', 'Alemania'), ('Nissan', 'Japón');

-- Modelos (Relacionados con las marcas anteriores)
INSERT INTO modelos (id_marca, nombre, segmento) VALUES 
(1, 'Corolla', 'Sedán'), (1, 'RAV4', 'SUV'),
(2, 'Serie 3', 'Sedán'), (2, 'X5', 'SUV'),
(3, 'Mustang', 'Deportivo'), (3, 'F-150', 'Pick-up'),
(4, 'Model 3', 'Eléctrico'), (4, 'Model Y', 'Eléctrico'),
(5, 'Tucson', 'SUV'), (6, 'A3', 'Compacto');

-- Clientes
INSERT INTO clientes (nombre, apellidos, dni, telefono, email, ciudad) VALUES 
('Antonio', 'Ramírez', '12345678A', '600111222', 'antonio@email.com', 'Madrid'),
('Beatriz', 'García', '23456789B', '600222333', 'beatriz@email.com', 'Barcelona'),
('Carlos', 'López', '34567890C', '600333444', 'carlos@email.com', 'Valencia'),
('Diana', 'Martínez', '45678901D', '600444555', 'diana@email.com', 'Sevilla'),
('Elena', 'Sanz', '56789012E', '600555666', 'elena@email.com', 'Zaragoza');

-- Vendedores
INSERT INTO vendedores (nombre, apellidos, fecha_ingreso, comision_pct) VALUES 
('Marcos', 'Pérez', '2020-01-15', 1.50),
('Lucía', 'Gómez', '2021-06-10', 1.20),
('Jorge', 'Blanco', '2022-03-05', 1.00);

-- INSERCIÓN MASIVA DE COCHES (150 registros)
-- Usamos generate_series para crear datos aleatorios coherentes
INSERT INTO coches (id_modelo, vin, color, anio, precio_base, estado, tipo, kilometraje)
SELECT 
    floor(random() * 10 + 1)::int,                    -- id_modelo entre 1 y 10
    upper(substring(md5(random()::text) from 1 for 17)), -- VIN aleatorio
    (ARRAY['Blanco', 'Negro', 'Gris', 'Azul', 'Rojo'])[floor(random() * 5 + 1)],
    (floor(random() * (2024 - 2018 + 1) + 2018))::int,
    (random() * (60000 - 15000) + 15000)::decimal(12,2),
    (ARRAY['Disponible', 'Vendido', 'Reservado', 'Mantenimiento'])[floor(random() * 4 + 1)]::tipo_estado,
    (ARRAY['Nuevo', 'Ocasión'])[floor(random() * 2 + 1)]::tipo_vehiculo,
    CASE 
        WHEN random() > 0.6 THEN floor(random() * 100000)::int 
        ELSE 0 
    END
FROM generate_series(1, 150);

-- INSERCIÓN DE VENTAS (100 registros)
-- Basado en los coches que tienen estado 'Vendido'
INSERT INTO ventas (id_coche, id_cliente, id_vendedor, fecha_venta, precio_final, metodo_pago)
SELECT 
    c.id_coche,
    floor(random() * 5 + 1)::int, -- Clientes del 1 al 5
    floor(random() * 3 + 1)::int, -- Vendedores del 1 al 3
    now() - (random() * interval '365 days'),
    c.precio_base * 0.95,
    (ARRAY['Contado', 'Financiado', 'Leasing'])[floor(random() * 3 + 1)]::tipo_pago
FROM (SELECT id_coche, precio_base FROM coches WHERE estado = 'Vendido' LIMIT 100) c;

-- INSERCIÓN DE REVISIONES (120 registros)
INSERT INTO revisiones (id_coche, fecha_revision, descripcion, coste)
SELECT 
    floor(random() * 150 + 1)::int,
    now() - (random() * interval '500 days'),
    'Revisión técnica rutinaria y cambio de líquidos.',
    (random() * (800 - 50) + 50)::decimal(10,2)
FROM generate_series(1, 120);

COMMIT;

-- 5. CONSULTAS DE PRUEBA (Análisis de datos)
-- -----------------------------------------------------------------------------

-- A. Reporte de ventas: ¿Qué hemos vendido y quién lo ha vendido?
SELECT 
    v.fecha_venta::date, 
    ma.nombre AS marca, 
    mo.nombre AS modelo, 
    cl.nombre || ' ' || cl.apellidos AS cliente,
    ve.nombre AS vendedor,
    v.precio_final
FROM ventas v
JOIN coches c ON v.id_coche = c.id_coche
JOIN modelos mo ON c.id_modelo = mo.id_modelo
JOIN marcas ma ON mo.id_marca = ma.id_marca
JOIN clientes cl ON v.id_cliente = cl.id_cliente
JOIN vendedores ve ON v.id_vendedor = ve.id_vendedor
ORDER BY v.fecha_venta DESC
LIMIT 10;

-- B. Inventario actual por estado
SELECT estado, COUNT(*) as cantidad, ROUND(AVG(precio_base), 2) as precio_promedio
FROM coches
GROUP BY estado;

-- C. Top 3 Clientes que más han invertido (incluyendo mantenimiento)
SELECT 
    cl.nombre, 
    cl.apellidos, 
    SUM(v.precio_final) as total_compra
FROM clientes cl
JOIN ventas v ON cl.id_cliente = v.id_cliente
GROUP BY cl.id_cliente, cl.nombre, cl.apellidos
ORDER BY total_compra DESC
LIMIT 3;

-- D. Coches con mayor coste acumulado en revisiones
SELECT c.vin, mo.nombre, COUNT(r.id_revision) as num_revisiones, SUM(r.coste) as coste_total
FROM revisiones r
JOIN coches c ON r.id_coche = c.id_coche
JOIN modelos mo ON c.id_modelo = mo.id_modelo
GROUP BY c.id_coche, c.vin, mo.nombre
HAVING SUM(r.coste) > 500
ORDER BY coste_total DESC;