-- =============================================================================
-- SISTEMA DE GESTIÓN AEROPORTUARIA 
-- Oracle XE
-- Autor: Efrén Sánchez / Adaptación: IA
-- =============================================================================

-- 1. LIMPIEZA DE TABLAS (Usando bloque anónimo para evitar errores si no existen)
-- -----------------------------------------------------------------------------
BEGIN
   FOR r IN (SELECT table_name FROM user_tables WHERE table_name IN 
     ('EQUIPAJE', 'RESERVAS', 'VUELOS', 'AVIONES', 'AEROPUERTOS', 'AEROLINEAS', 'PASAJEROS'))
   LOOP
      EXECUTE IMMEDIATE 'DROP TABLE ' || r.table_name || ' CASCADE CONSTRAINTS';
   END LOOP;
END;
/

-- 2. DDL: DEFINICIÓN DE TABLAS
-- -----------------------------------------------------------------------------

CREATE TABLE pasajeros (
    id_pasajero NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL,
    apellidos VARCHAR2(100) NOT NULL,
    pasaporte VARCHAR2(20) UNIQUE NOT NULL,
    nacionalidad VARCHAR2(50),
    email VARCHAR2(100) UNIQUE,
    telefono VARCHAR2(20)
);

CREATE TABLE aerolineas (
    id_aerolinea NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    codigo_iata VARCHAR2(3) UNIQUE NOT NULL,
    pais_origen VARCHAR2(50)
);

CREATE TABLE aeropuertos (
    id_aeropuerto NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    codigo_iata VARCHAR2(3) UNIQUE NOT NULL,
    ciudad VARCHAR2(50) NOT NULL,
    pais VARCHAR2(50) NOT NULL
);

CREATE TABLE aviones (
    id_avion NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    modelo VARCHAR2(50) NOT NULL,
    capacidad_pasajeros NUMBER NOT NULL,
    id_aerolinea NUMBER NOT NULL,
    CONSTRAINT fk_avion_aerolinea FOREIGN KEY (id_aerolinea) REFERENCES aerolineas(id_aerolinea) ON DELETE CASCADE
);

CREATE TABLE vuelos (
    id_vuelo NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_vuelo VARCHAR2(10) UNIQUE NOT NULL,
    id_aerolinea NUMBER NOT NULL,
    id_origen NUMBER NOT NULL,
    id_destino NUMBER NOT NULL,
    id_avion NUMBER NOT NULL,
    fecha_salida DATE NOT NULL,
    fecha_llegada DATE NOT NULL,
    estado VARCHAR2(20) DEFAULT 'Programado',
    precio_base NUMBER(10,2) NOT NULL,
    CONSTRAINT chk_estado_vuelo CHECK (estado IN ('Programado', 'En Vuelo', 'Aterrizado', 'Retrasado', 'Cancelado')),
    CONSTRAINT fk_vuelo_aerolinea FOREIGN KEY (id_aerolinea) REFERENCES aerolineas(id_aerolinea),
    CONSTRAINT fk_vuelo_origen FOREIGN KEY (id_origen) REFERENCES aeropuertos(id_aeropuerto),
    CONSTRAINT fk_vuelo_destino FOREIGN KEY (id_destino) REFERENCES aeropuertos(id_aeropuerto),
    CONSTRAINT fk_vuelo_avion FOREIGN KEY (id_avion) REFERENCES aviones(id_avion)
);

CREATE TABLE reservas (
    id_reserva NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pasajero NUMBER NOT NULL,
    id_vuelo NUMBER NOT NULL,
    fecha_reserva TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    asiento VARCHAR2(5) NOT NULL,
    clase VARCHAR2(20) DEFAULT 'Turista',
    precio_final NUMBER(10,2) NOT NULL,
    CONSTRAINT chk_clase_reserva CHECK (clase IN ('Turista', 'Business', 'Primera')),
    CONSTRAINT fk_reserva_pasajero FOREIGN KEY (id_pasajero) REFERENCES pasajeros(id_pasajero),
    CONSTRAINT fk_reserva_vuelo FOREIGN KEY (id_vuelo) REFERENCES vuelos(id_vuelo)
);

CREATE TABLE equipaje (
    id_equipaje NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_reserva NUMBER NOT NULL,
    peso_kg NUMBER(5,2) NOT NULL,
    tipo VARCHAR2(20) DEFAULT 'Bodega',
    CONSTRAINT chk_tipo_equipaje CHECK (tipo IN ('Mano', 'Bodega')),
    CONSTRAINT fk_equipaje_reserva FOREIGN KEY (id_reserva) REFERENCES reservas(id_reserva) ON DELETE CASCADE
);

-- 3. DML: CARGA DE DATOS
-- -----------------------------------------------------------------------------

-- AEROLÍNEAS
INSERT INTO aerolineas (nombre, codigo_iata, pais_origen) VALUES ('Iberia', 'IBE', 'España');
INSERT INTO aerolineas (nombre, codigo_iata, pais_origen) VALUES ('Emirates', 'UAE', 'Emiratos Árabes');
INSERT INTO aerolineas (nombre, codigo_iata, pais_origen) VALUES ('Lufthansa', 'DLH', 'Alemania');
INSERT INTO aerolineas (nombre, codigo_iata, pais_origen) VALUES ('Delta Air Lines', 'DAL', 'USA');
INSERT INTO aerolineas (nombre, codigo_iata, pais_origen) VALUES ('Ryanair', 'RYR', 'Irlanda');
INSERT INTO aerolineas (nombre, codigo_iata, pais_origen) VALUES ('Air France', 'AFR', 'Francia');
INSERT INTO aerolineas (nombre, codigo_iata, pais_origen) VALUES ('Qatar Airways', 'QTR', 'Qatar');
INSERT INTO aerolineas (nombre, codigo_iata, pais_origen) VALUES ('LATAM', 'LAN', 'Chile');
INSERT INTO aerolineas (nombre, codigo_iata, pais_origen) VALUES ('Japan Airlines', 'JAL', 'Japón');
INSERT INTO aerolineas (nombre, codigo_iata, pais_origen) VALUES ('British Airways', 'BAW', 'Reino Unido');
INSERT INTO aerolineas (nombre, codigo_iata, pais_origen) VALUES ('Aeroméxico', 'AMX', 'México');
INSERT INTO aerolineas (nombre, codigo_iata, pais_origen) VALUES ('Turkish Airlines', 'THY', 'Turquía');

-- AEROPUERTOS
INSERT INTO aeropuertos (nombre, codigo_iata, ciudad, pais) VALUES ('Adolfo Suárez Madrid-Barajas', 'MAD', 'Madrid', 'España');
INSERT INTO aeropuertos (nombre, codigo_iata, ciudad, pais) VALUES ('John F. Kennedy', 'JFK', 'Nueva York', 'USA');
INSERT INTO aeropuertos (nombre, codigo_iata, ciudad, pais) VALUES ('Narita International', 'NRT', 'Tokio', 'Japón');
INSERT INTO aeropuertos (nombre, codigo_iata, ciudad, pais) VALUES ('Heathrow', 'LHR', 'Londres', 'Reino Unido');
INSERT INTO aeropuertos (nombre, codigo_iata, ciudad, pais) VALUES ('Charles de Gaulle', 'CDG', 'París', 'Francia');
INSERT INTO aeropuertos (nombre, codigo_iata, ciudad, pais) VALUES ('Dubai International', 'DXB', 'Dubai', 'EAU');
INSERT INTO aeropuertos (nombre, codigo_iata, ciudad, pais) VALUES ('El Dorado', 'BOG', 'Bogotá', 'Colombia');
INSERT INTO aeropuertos (nombre, codigo_iata, ciudad, pais) VALUES ('Benito Juárez', 'MEX', 'Ciudad de México', 'México');
INSERT INTO aeropuertos (nombre, codigo_iata, ciudad, pais) VALUES ('Frankfurt Airport', 'FRA', 'Frankfurt', 'Alemania');
INSERT INTO aeropuertos (nombre, codigo_iata, ciudad, pais) VALUES ('Sydney Airport', 'SYD', 'Sydney', 'Australia');
INSERT INTO aeropuertos (nombre, codigo_iata, ciudad, pais) VALUES ('El Prat', 'BCN', 'Barcelona', 'España');
INSERT INTO aeropuertos (nombre, codigo_iata, ciudad, pais) VALUES ('Ministro Pistarini', 'EZE', 'Buenos Aires', 'Argentina');

-- AVIONES
INSERT INTO aviones (modelo, capacidad_pasajeros, id_aerolinea) VALUES ('Airbus A350', 350, 1);
INSERT INTO aviones (modelo, capacidad_pasajeros, id_aerolinea) VALUES ('Airbus A320', 180, 1);
INSERT INTO aviones (modelo, capacidad_pasajeros, id_aerolinea) VALUES ('Boeing 777', 400, 2);
INSERT INTO aviones (modelo, capacidad_pasajeros, id_aerolinea) VALUES ('Airbus A380', 550, 2);
INSERT INTO aviones (modelo, capacidad_pasajeros, id_aerolinea) VALUES ('Boeing 747', 410, 3);

-- PASAJEROS
INSERT INTO pasajeros (nombre, apellidos, pasaporte, nacionalidad, email, telefono) 
VALUES ('Juan', 'García López', 'P-1001', 'España', 'juan.garcia@email.com', '+34600111222');
INSERT INTO pasajeros (nombre, apellidos, pasaporte, nacionalidad, email, telefono) 
VALUES ('Maria', 'Rodríguez Silva', 'P-1002', 'México', 'm.rodriguez@email.com', '+52555123456');
INSERT INTO pasajeros (nombre, apellidos, pasaporte, nacionalidad, email, telefono) 
VALUES ('John', 'Smith', 'P-1003', 'USA', 'john.smith@email.com', '+12025550101');

-- VUELOS (Usando formato TO_DATE para evitar errores de NLS_DATE_FORMAT)
INSERT INTO vuelos (numero_vuelo, id_aerolinea, id_origen, id_destino, id_avion, fecha_salida, fecha_llegada, estado, precio_base) 
VALUES ('IB101', 1, 1, 2, 1, TO_DATE('2024-10-01 10:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-10-01 18:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Aterrizado', 450.00);

INSERT INTO vuelos (numero_vuelo, id_aerolinea, id_origen, id_destino, id_avion, fecha_salida, fecha_llegada, estado, precio_base) 
VALUES ('UAE201', 2, 6, 3, 3, TO_DATE('2024-11-10 03:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-11-10 15:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Aterrizado', 850.00);

-- Inserción masiva de pasajeros simulada (Lógica compatible Oracle)
INSERT INTO pasajeros (nombre, apellidos, pasaporte, nacionalidad, email, telefono)
SELECT nombre || ' II', apellidos || ' Jr', pasaporte || 'X', nacionalidad, 'alt.' || email, telefono 
FROM pasajeros WHERE ROWNUM <= 10;

-- RESERVAS (Simulación lógica de cruce)
INSERT INTO reservas (id_pasajero, id_vuelo, asiento, clase, precio_final)
SELECT 
    p.id_pasajero, 
    v.id_vuelo, 
    FLOOR(DBMS_RANDOM.VALUE(1, 30)) || CHR(65 + FLOOR(DBMS_RANDOM.VALUE(0, 6))), 
    CASE WHEN DBMS_RANDOM.VALUE(0, 1) > 0.8 THEN 'Business' ELSE 'Turista' END,
    v.precio_base * (1 + DBMS_RANDOM.VALUE(0, 1))
FROM pasajeros p
CROSS JOIN (SELECT id_vuelo, precio_base FROM vuelos WHERE ROWNUM <= 2) v
WHERE ROWNUM <= 50;

COMMIT;

-- 4. CONSULTAS DE PRUEBA
-- -----------------------------------------------------------------------------

-- 1. INFORME MAESTRO
SELECT 
    v.numero_vuelo, 
    a.nombre AS aerolinea,
    p.nombre || ' ' || p.apellidos AS pasajero,
    r.asiento,
    r.clase,
    ao.codigo_iata AS origen,
    ad.codigo_iata AS destino
FROM reservas r
JOIN pasajeros p ON r.id_pasajero = p.id_pasajero
JOIN vuelos v ON r.id_vuelo = v.id_vuelo
JOIN aerolineas a ON v.id_aerolinea = a.id_aerolinea
JOIN aeropuertos ao ON v.id_origen = ao.id_aeropuerto
JOIN aeropuertos ad ON v.id_destino = ad.id_aeropuerto
ORDER BY v.numero_vuelo;

-- 2. TABLÓN DE ANUNCIOS (Uso de FETCH FIRST en lugar de LIMIT)
SELECT 
    v.numero_vuelo, 
    a.nombre AS aerolinea, 
    o.ciudad AS ciudad_origen, 
    d.ciudad AS ciudad_destino, 
    v.fecha_salida, 
    v.estado
FROM vuelos v
JOIN aerolineas a ON v.id_aerolinea = a.id_aerolinea
JOIN aeropuertos o ON v.id_origen = o.id_aeropuerto
JOIN aeropuertos d ON v.id_destino = d.id_aeropuerto
ORDER BY v.fecha_salida ASC
FETCH FIRST 20 ROWS ONLY;

-- 3. ESTADÍSTICAS FINANCIERAS
SELECT 
    a.nombre AS aerolinea, 
    COUNT(r.id_reserva) AS total_pasajeros,
    SUM(r.precio_final) AS ingresos_totales
FROM aerolineas a
JOIN vuelos v ON a.id_aerolinea = v.id_aerolinea
JOIN reservas r ON v.id_vuelo = r.id_vuelo
GROUP BY a.id_aerolinea, a.nombre
HAVING SUM(r.precio_final) > 0
ORDER BY ingresos_totales DESC;

-- 4. CÁLCULO DE DURACIÓN (En Oracle, la resta de fechas da días, multiplicamos para horas)
SELECT 
    numero_vuelo, 
    fecha_salida, 
    fecha_llegada,
    ROUND((fecha_llegada - fecha_salida) * 24, 2) || ' Horas' AS duracion_estimada
FROM vuelos
WHERE (fecha_llegada - fecha_salida) * 24 > 3;

-- 5. CONTROL DE VOLUMEN TOTAL
SELECT 'Aerolineas' as Tabla, COUNT(*) as Total FROM aerolineas
UNION ALL SELECT 'Aeropuertos', COUNT(*) FROM aeropuertos
UNION ALL SELECT 'Pasajeros', COUNT(*) FROM pasajeros
UNION ALL SELECT 'Vuelos', COUNT(*) FROM vuelos
UNION ALL SELECT 'Reservas', COUNT(*) FROM reservas;
