-- =============================================================================
-- SISTEMA DE GESTIÓN DE CONCESIONARIO
-- Oracle XE 
-- Autor: Efrén Sánchez / Optimización de datos: IA
-- =============================================================================

-- 1. LIMPIEZA DE TABLAS (PL/SQL para evitar errores si no existen)
BEGIN
   FOR t IN (SELECT table_name FROM user_tables WHERE table_name IN 
     ('REVISIONES', 'VENTAS', 'COCHES', 'MODELOS', 'MARCAS', 'VENDEDORES', 'CLIENTES'))
   LOOP
      EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
   END LOOP;
END;
/

-- 2. DEFINICIÓN DEL ESQUEMA (DDL)
-- -----------------------------------------------------------------------------

CREATE TABLE marcas (
    id_marca      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre        VARCHAR2(50) NOT NULL,
    pais_origen   VARCHAR2(50)
);

CREATE TABLE modelos (
    id_modelo     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_marca      NUMBER NOT NULL,
    nombre        VARCHAR2(50) NOT NULL,
    segmento      VARCHAR2(20) NOT NULL,
    CONSTRAINT chk_segmento CHECK (segmento IN ('SUV', 'Sedán', 'Compacto', 'Deportivo', 'Pick-up', 'Eléctrico')),
    CONSTRAINT fk_modelo_marca FOREIGN KEY (id_marca) REFERENCES marcas(id_marca)
);

CREATE TABLE coches (
    id_coche      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_modelo     NUMBER NOT NULL,
    vin           VARCHAR2(17) UNIQUE NOT NULL,
    color         VARCHAR2(30),
    anio          NUMBER(4) NOT NULL,
    precio_base   NUMBER(12,2) NOT NULL,
    estado        VARCHAR2(20) DEFAULT 'Disponible',
    tipo          VARCHAR2(10) DEFAULT 'Nuevo',
    kilometraje   NUMBER DEFAULT 0,
    CONSTRAINT chk_estado CHECK (estado IN ('Disponible', 'Reservado', 'Vendido', 'Mantenimiento')),
    CONSTRAINT chk_tipo CHECK (tipo IN ('Nuevo', 'Ocasión')),
    CONSTRAINT fk_coche_modelo FOREIGN KEY (id_modelo) REFERENCES modelos(id_modelo)
);

CREATE TABLE clientes (
    id_cliente    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre        VARCHAR2(50) NOT NULL,
    apellidos     VARCHAR2(100) NOT NULL,
    dni           VARCHAR2(15) UNIQUE NOT NULL,
    telefono      VARCHAR2(20),
    email         VARCHAR2(100),
    ciudad        VARCHAR2(50)
);

CREATE TABLE vendedores (
    id_vendedor   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre        VARCHAR2(50) NOT NULL,
    apellidos     VARCHAR2(100) NOT NULL,
    fecha_ingreso DATE NOT NULL,
    comision_pct  NUMBER(4,2) DEFAULT 1.00
);

CREATE TABLE ventas (
    id_venta      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_coche      NUMBER NOT NULL,
    id_cliente    NUMBER NOT NULL,
    id_vendedor   NUMBER NOT NULL,
    fecha_venta   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    precio_final  NUMBER(12,2) NOT NULL,
    metodo_pago   VARCHAR2(15) NOT NULL,
    CONSTRAINT chk_pago CHECK (metodo_pago IN ('Contado', 'Financiado', 'Leasing')),
    CONSTRAINT fk_venta_coche FOREIGN KEY (id_coche) REFERENCES coches(id_coche),
    CONSTRAINT fk_venta_cliente FOREIGN KEY (id_cliente) REFERENCES clientes(id_cliente),
    CONSTRAINT fk_venta_vendedor FOREIGN KEY (id_vendedor) REFERENCES vendedores(id_vendedor)
);

CREATE TABLE revisiones (
    id_revision   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_coche      NUMBER NOT NULL,
    fecha_revision DATE NOT NULL,
    descripcion   VARCHAR2(500),
    coste         NUMBER(10,2) NOT NULL,
    CONSTRAINT fk_revision_coche FOREIGN KEY (id_coche) REFERENCES coches(id_coche)
);

-- 3. CARGA DE DATOS (DML)
-- -----------------------------------------------------------------------------

-- Marcas
INSERT INTO marcas (nombre, pais_origen) VALUES ('Toyota', 'Japón');
INSERT INTO marcas (nombre, pais_origen) VALUES ('BMW', 'Alemania');
INSERT INTO marcas (nombre, pais_origen) VALUES ('Ford', 'USA');
INSERT INTO marcas (nombre, pais_origen) VALUES ('Tesla', 'USA');
INSERT INTO marcas (nombre, pais_origen) VALUES ('Hyundai', 'Corea del Sur');
INSERT INTO marcas (nombre, pais_origen) VALUES ('Audi', 'Alemania');
INSERT INTO marcas (nombre, pais_origen) VALUES ('Mercedes-Benz', 'Alemania');
INSERT INTO marcas (nombre, pais_origen) VALUES ('Volkswagen', 'Alemania');

-- Modelos
INSERT INTO modelos (id_marca, nombre, segmento) VALUES (1, 'Corolla', 'Sedán');
INSERT INTO modelos (id_marca, nombre, segmento) VALUES (1, 'RAV4', 'SUV');
INSERT INTO modelos (id_marca, nombre, segmento) VALUES (2, 'Serie 3', 'Sedán');
INSERT INTO modelos (id_marca, nombre, segmento) VALUES (2, 'X5', 'SUV');
INSERT INTO modelos (id_marca, nombre, segmento) VALUES (3, 'Mustang', 'Deportivo');
INSERT INTO modelos (id_marca, nombre, segmento) VALUES (3, 'F-150', 'Pick-up');
INSERT INTO modelos (id_marca, nombre, segmento) VALUES (4, 'Model 3', 'Eléctrico');
INSERT INTO modelos (id_marca, nombre, segmento) VALUES (5, 'Tucson', 'SUV');
INSERT INTO modelos (id_marca, nombre, segmento) VALUES (6, 'A3', 'Compacto');
INSERT INTO modelos (id_marca, nombre, segmento) VALUES (7, 'Clase C', 'Sedán');
INSERT INTO modelos (id_marca, nombre, segmento) VALUES (8, 'Golf', 'Compacto');

-- Vendedores (8)
INSERT INTO vendedores (nombre, apellidos, fecha_ingreso, comision_pct) VALUES ('Javier', 'Gómez Martín', TO_DATE('2020-05-15','YYYY-MM-DD'), 1.50);
INSERT INTO vendedores (nombre, apellidos, fecha_ingreso, comision_pct) VALUES ('Lucía', 'Fernández Ruiz', TO_DATE('2022-01-10','YYYY-MM-DD'), 1.20);
INSERT INTO vendedores (nombre, apellidos, fecha_ingreso, comision_pct) VALUES ('Marcos', 'Pérez Soria', TO_DATE('2023-03-01','YYYY-MM-DD'), 1.00);
INSERT INTO vendedores (nombre, apellidos, fecha_ingreso, comision_pct) VALUES ('Elena', 'Blanco Ortiz', TO_DATE('2021-11-20','YYYY-MM-DD'), 1.30);
INSERT INTO vendedores (nombre, apellidos, fecha_ingreso, comision_pct) VALUES ('Roberto', 'Sánchez Cano', TO_DATE('2019-06-14','YYYY-MM-DD'), 1.80);

-- Clientes (15 de ejemplo)
INSERT INTO clientes (nombre, apellidos, dni, telefono, email, ciudad) VALUES ('Antonio', 'Ramírez Soler', '12345678X', '600111222', 'antonio@mail.com', 'Madrid');
INSERT INTO clientes (nombre, apellidos, dni, telefono, email, ciudad) VALUES ('Beatriz', 'Luna Méndez', '87654321Y', '600333444', 'b.luna@mail.com', 'Barcelona');
INSERT INTO clientes (nombre, apellidos, dni, telefono, email, ciudad) VALUES ('Carlos', 'Sanz Vega', '45678901Z', '600555666', 'csanz@mail.com', 'Sevilla');

-- INSERCIÓN MASIVA DE COCHES (150 registros) usando un bloque PL/SQL
BEGIN
   FOR i IN 1..150 LOOP
      INSERT INTO coches (id_modelo, vin, color, anio, precio_base, estado, tipo, kilometraje)
      VALUES (
         TRUNC(DBMS_RANDOM.VALUE(1, 11)), -- Modelo aleatorio
         'VIN' || LPAD(i, 14, '0'),       -- VIN único
         CASE TRUNC(DBMS_RANDOM.VALUE(1, 6))
            WHEN 1 THEN 'Blanco' WHEN 2 THEN 'Negro' WHEN 3 THEN 'Gris' WHEN 4 THEN 'Rojo' ELSE 'Azul' END,
         TRUNC(DBMS_RANDOM.VALUE(2018, 2025)),
         TRUNC(DBMS_RANDOM.VALUE(15000, 60000)),
         CASE TRUNC(DBMS_RANDOM.VALUE(1, 5))
            WHEN 1 THEN 'Disponible' WHEN 2 THEN 'Vendido' WHEN 3 THEN 'Reservado' ELSE 'Mantenimiento' END,
         CASE WHEN DBMS_RANDOM.VALUE(0, 1) > 0.5 THEN 'Nuevo' ELSE 'Ocasión' END,
         CASE WHEN DBMS_RANDOM.VALUE(0, 1) > 0.7 THEN TRUNC(DBMS_RANDOM.VALUE(10000, 120000)) ELSE 0 END
      );
   END LOOP;
END;
/

-- INSERCIÓN MASIVA DE VENTAS (100 registros)
-- Solo para coches que marcamos arriba como 'Vendido'
BEGIN
   FOR rec IN (SELECT id_coche, precio_base FROM coches WHERE estado = 'Vendido' AND ROWNUM <= 100) LOOP
      INSERT INTO ventas (id_coche, id_cliente, id_vendedor, fecha_venta, precio_final, metodo_pago)
      VALUES (
         rec.id_coche,
         TRUNC(DBMS_RANDOM.VALUE(1, 4)), -- Cliente entre los 3 creados
         TRUNC(DBMS_RANDOM.VALUE(1, 6)), -- Vendedor entre los 5 creados
         CURRENT_TIMESTAMP - DBMS_RANDOM.VALUE(1, 365),
         rec.precio_base * 0.95,        -- Descuento del 5%
         CASE TRUNC(DBMS_RANDOM.VALUE(1, 4))
            WHEN 1 THEN 'Contado' WHEN 2 THEN 'Financiado' ELSE 'Leasing' END
      );
   END LOOP;
END;
/

-- INSERCIÓN MASIVA DE REVISIONES (100 registros)
BEGIN
   FOR i IN 1..100 LOOP
      INSERT INTO revisiones (id_coche, fecha_revision, descripcion, coste)
      VALUES (
         TRUNC(DBMS_RANDOM.VALUE(1, 151)),
         SYSDATE - DBMS_RANDOM.VALUE(1, 500),
         'Mantenimiento preventivo tipo ' || TRUNC(DBMS_RANDOM.VALUE(1, 5)),
         DBMS_RANDOM.VALUE(100, 1200)
      );
   END LOOP;
END;
/

COMMIT;

-- 4. CONSULTAS DE PRUEBA (Sintaxis Oracle)
-- -----------------------------------------------------------------------------

-- A. Stock actual con nombre de marca y modelo
SELECT m.nombre AS marca, mo.nombre AS modelo, c.vin, c.precio_base, c.estado
FROM coches c
JOIN modelos mo ON c.id_modelo = mo.id_modelo
JOIN marcas m ON mo.id_marca = m.id_marca
WHERE c.estado = 'Disponible'
ORDER BY c.precio_base DESC;

-- B. Total de ventas por vendedor
SELECT v.nombre, v.apellidos, COUNT(ve.id_venta) AS total_unidades, SUM(ve.precio_final) AS total_euros
FROM vendedores v
LEFT JOIN ventas ve ON v.id_vendedor = ve.id_vendedor
GROUP BY v.id_vendedor, v.nombre, v.apellidos
ORDER BY total_euros DESC;

-- C. Gastos de taller por coche (Top 10 más caros)
SELECT * FROM (
    SELECT c.vin, mo.nombre AS modelo, SUM(r.coste) AS total_gastado
    FROM revisiones r
    JOIN coches c ON r.id_coche = c.id_coche
    JOIN modelos mo ON c.id_modelo = mo.id_modelo
    GROUP BY c.vin, mo.nombre
    ORDER BY total_gastado DESC
) WHERE ROWNUM <= 10;