-- =============================================================================
-- SISTEMA DE GESTIÓN HOTELERA
-- Oracle XE (18c, 21c, 23c)
-- Autor: Efrén Sánchez / Optimización de datos: IA
-- =============================================================================

-- 1. LIMPIEZA DE TABLAS (Usamos un bloque para evitar errores si no existen)
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE consumos_extras CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE servicios CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE reservas CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE habitaciones CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE tipos_habitacion CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE huespedes CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

-- 2. DEFINICIÓN DEL ESQUEMA (DDL)
-- -----------------------------------------------------------------------------

CREATE TABLE tipos_habitacion (
    id_tipo            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre             VARCHAR2(50) NOT NULL,
    precio_noche       NUMBER(10,2) NOT NULL,
    capacidad_personas NUMBER(3) NOT NULL,
    descripcion        CLOB
);

CREATE TABLE habitaciones (
    id_habitacion NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero        VARCHAR2(10) NOT NULL UNIQUE,
    id_tipo       NUMBER NOT NULL,
    piso          NUMBER(3) NOT NULL,
    estado        VARCHAR2(20) DEFAULT 'Disponible',
    CONSTRAINT fk_hab_tipo FOREIGN KEY (id_tipo) REFERENCES tipos_habitacion(id_tipo),
    CONSTRAINT chk_estado_hab CHECK (estado IN ('Disponible', 'Ocupada', 'Limpieza', 'Mantenimiento'))
);

CREATE TABLE huespedes (
    id_huesped   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre       VARCHAR2(50) NOT NULL,
    apellidos    VARCHAR2(100) NOT NULL,
    documento_id VARCHAR2(20) NOT NULL UNIQUE,
    email        VARCHAR2(100),
    telefono     VARCHAR2(20),
    pais         VARCHAR2(50)
);

CREATE TABLE reservas (
    id_reserva        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_huesped        NUMBER NOT NULL,
    id_habitacion     NUMBER NOT NULL,
    fecha_reserva     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fecha_entrada     DATE NOT NULL,
    fecha_salida      DATE NOT NULL,
    estado_reserva    VARCHAR2(20) DEFAULT 'Pendiente',
    total_alojamiento NUMBER(10,2) DEFAULT 0.00,
    CONSTRAINT fk_res_huesped FOREIGN KEY (id_huesped) REFERENCES huespedes(id_huesped),
    CONSTRAINT fk_res_hab FOREIGN KEY (id_habitacion) REFERENCES habitaciones(id_habitacion),
    CONSTRAINT chk_fechas CHECK (fecha_salida > fecha_entrada),
    CONSTRAINT chk_estado_res CHECK (estado_reserva IN ('Confirmada', 'Pendiente', 'Cancelada', 'Finalizada'))
);

CREATE TABLE servicios (
    id_servicio NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      VARCHAR2(50) NOT NULL,
    precio      NUMBER(10,2) NOT NULL
);

CREATE TABLE consumos_extras (
    id_consumo    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_reserva    NUMBER NOT NULL,
    id_servicio   NUMBER NOT NULL,
    fecha_consumo DATE DEFAULT SYSDATE,
    cantidad      NUMBER(3) DEFAULT 1,
    subtotal      NUMBER(10,2) NOT NULL,
    CONSTRAINT fk_cons_reserva FOREIGN KEY (id_reserva) REFERENCES reservas(id_reserva),
    CONSTRAINT fk_cons_servicio FOREIGN KEY (id_servicio) REFERENCES servicios(id_servicio)
);

-- 3. CARGA DE DATOS (DML)
-- -----------------------------------------------------------------------------

-- Inserción de Tipos de Habitación
INSERT INTO tipos_habitacion (nombre, precio_noche, capacidad_personas, descripcion) VALUES ('Económica Single', 35.00, 1, 'Cama sencilla.');
INSERT INTO tipos_habitacion (nombre, precio_noche, capacidad_personas, descripcion) VALUES ('Estándar Doble', 65.00, 2, 'Dos camas o matrimonial.');
INSERT INTO tipos_habitacion (nombre, precio_noche, capacidad_personas, descripcion) VALUES ('Junior Suite', 110.00, 2, 'Mini bar incluido.');
INSERT INTO tipos_habitacion (nombre, precio_noche, capacidad_personas, descripcion) VALUES ('Familiar Deluxe', 150.00, 4, 'Dos habitaciones conectadas.');
INSERT INTO tipos_habitacion (nombre, precio_noche, capacidad_personas, descripcion) VALUES ('Suite Presidencial', 300.00, 2, 'Jacuzzi y servicios VIP.');

-- Inserción de Habitaciones (20 habitaciones)
BEGIN
    FOR i IN 1..5 LOOP INSERT INTO habitaciones (numero, id_tipo, piso, estado) VALUES ('10'||i, 1, 1, 'Disponible'); END LOOP;
    FOR i IN 1..5 LOOP INSERT INTO habitaciones (numero, id_tipo, piso, estado) VALUES ('20'||i, 2, 2, 'Disponible'); END LOOP;
    FOR i IN 1..5 LOOP INSERT INTO habitaciones (numero, id_tipo, piso, estado) VALUES ('30'||i, 3, 3, 'Disponible'); END LOOP;
    FOR i IN 1..5 LOOP INSERT INTO habitaciones (numero, id_tipo, piso, estado) VALUES ('40'||i, 5, 4, 'Disponible'); END LOOP;
END;
/

-- Inserción de Servicios
INSERT INTO servicios (nombre, precio) VALUES ('Desayuno Buffet', 15.00);
INSERT INTO servicios (nombre, precio) VALUES ('Lavandería Express', 20.00);
INSERT INTO servicios (nombre, precio) VALUES ('Spa & Masaje', 45.00);
INSERT INTO servicios (nombre, precio) VALUES ('Parking', 10.00);
INSERT INTO servicios (nombre, precio) VALUES ('Minibar Pack', 25.00);

-- Inserción Masiva de Huéspedes (100 registros)
BEGIN
    FOR i IN 1..100 LOOP
        INSERT INTO huespedes (nombre, apellidos, documento_id, email, telefono, pais)
        VALUES (
            'Nombre_' || i, 
            'Apellido_' || i, 
            'DOC' || (1000 + i), 
            'usuario' || i || '@correo.com', 
            '555-' || (1000 + i), 
            CASE MOD(i, 3) WHEN 0 THEN 'España' WHEN 1 THEN 'México' ELSE 'Colombia' END
        );
    END LOOP;
END;
/

-- Inserción Masiva de Reservas (120 registros)
BEGIN
    FOR i IN 1..120 LOOP
        INSERT INTO reservas (id_huesped, id_habitacion, fecha_entrada, fecha_salida, estado_reserva, total_alojamiento)
        VALUES (
            TRUNC(DBMS_RANDOM.VALUE(1, 101)), -- ID Huésped aleatorio
            TRUNC(DBMS_RANDOM.VALUE(1, 21)),  -- ID Habitación aleatoria
            SYSDATE - TRUNC(DBMS_RANDOM.VALUE(1, 100)), -- Entrada en los últimos 100 días
            SYSDATE + TRUNC(DBMS_RANDOM.VALUE(1, 10)),  -- Salida en los próximos 10 días
            CASE MOD(i, 4) WHEN 0 THEN 'Finalizada' WHEN 1 THEN 'Confirmada' WHEN 2 THEN 'Pendiente' ELSE 'Cancelada' END,
            DBMS_RANDOM.VALUE(100, 1000)
        );
    END LOOP;
END;
/

-- Inserción Masiva de Consumos Extras (150 registros)
BEGIN
    FOR i IN 1..150 LOOP
        DECLARE
            v_precio_serv NUMBER;
            v_id_serv     NUMBER := TRUNC(DBMS_RANDOM.VALUE(1, 6));
            v_cant        NUMBER := TRUNC(DBMS_RANDOM.VALUE(1, 4));
        BEGIN
            SELECT precio INTO v_precio_serv FROM servicios WHERE id_servicio = v_id_serv;
            
            INSERT INTO consumos_extras (id_reserva, id_servicio, cantidad, subtotal)
            VALUES (
                TRUNC(DBMS_RANDOM.VALUE(1, 121)), -- ID Reserva aleatoria
                v_id_serv,
                v_cant,
                v_precio_serv * v_cant
            );
        END;
    END LOOP;
END;
/

COMMIT;

-- 4. CONSULTAS DE PRUEBA
-- -----------------------------------------------------------------------------

-- A. Reporte de ocupación y total por reserva (Check-out)
SELECT 
    r.id_reserva, 
    h.nombre || ' ' || h.apellidos AS huesped, 
    r.total_alojamiento AS costo_estancia,
    NVL(SUM(ce.subtotal), 0) AS total_servicios,
    (r.total_alojamiento + NVL(SUM(ce.subtotal), 0)) AS gran_total
FROM reservas r
JOIN huespedes h ON r.id_huesped = h.id_huesped
LEFT JOIN consumos_extras ce ON r.id_reserva = ce.id_reserva
GROUP BY r.id_reserva, h.nombre, h.apellidos, r.total_alojamiento
FETCH FIRST 10 ROWS ONLY;

-- B. Habitaciones disponibles de tipo 'Suite' o 'Económica'
SELECT hab.numero, th.nombre as tipo, hab.piso
FROM habitaciones hab
JOIN tipos_habitacion th ON hab.id_tipo = th.id_tipo
WHERE hab.estado = 'Disponible';

-- C. Total recaudado por país de origen del huésped
SELECT h.pais, SUM(r.total_alojamiento) as total_ingresos
FROM huespedes h
JOIN reservas r ON h.id_huesped = r.id_huesped
GROUP BY h.pais
ORDER BY total_ingresos DESC;