-- =============================================================================
-- SISTEMA DE GESTIÓN AEROPORTUARIA 
-- Volumen: +1000 Pasajeros, +600 Vuelos, +2000 Reservas
-- PostgreSQL
-- Autor: Efrén Sánchez / Adaptación: IA
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Nota: en este script declaramos las PK como INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
-- En el script con menos volumen de registros se declaran como SERIAL PRIMARY KEY
-- Diferencias y cuál elegir:
-- 1. SERIAL PRIMARY KEY (estilo clásico)
--     Es un "atajo" propio de PostgreSQL. Cuando usas SERIAL, PostgreSQL crea automáticamente 
--     un objeto llamado SEQUENCE en segundo plano y vincula la columna a ese objeto. Es más 
--     corto de escribir. No forma parte del estándar SQL (es específico de Postgres). Además, 
--     si quieres cambiar los permisos, a veces hay que gestionar la secuencia por separado.
-- 2. GENERATED BY DEFAULT AS IDENTITY (estándar moderno)
--     Es la forma oficial del estándar SQL:2003. PostgreSQL la introdujo a partir de la versión 
--     10. Es compatible con otros motores (como Oracle, que fue el que usamos antes). Es más 
--     robusto y permite un mejor control (por ejemplo, puedes usar GENERATED ALWAYS para impedir 
--     que alguien inserte un ID manualmente por error). Es un poco más largo de escribir.


-- 1. LIMPIEZA DE TABLAS
-- -----------------------------------------------------------------------------
DROP TABLE IF EXISTS equipaje, reservas, vuelos, aviones, aeropuertos, aerolineas, pasajeros CASCADE;

-- 2. ESTRUCTURA (DDL)
-- -----------------------------------------------------------------------------

CREATE TABLE pasajeros (
    id_pasajero INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    apellidos VARCHAR(100) NOT NULL,
    pasaporte VARCHAR(20) UNIQUE NOT NULL,
    nacionalidad VARCHAR(50),
    email VARCHAR(100) UNIQUE,
    telefono VARCHAR(20)
);

CREATE TABLE aerolineas (
    id_aerolinea INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    codigo_iata VARCHAR(3) UNIQUE NOT NULL,
    pais_origen VARCHAR(50)
);

CREATE TABLE aeropuertos (
    id_aeropuerto INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    codigo_iata VARCHAR(5) UNIQUE NOT NULL,
    ciudad VARCHAR(50) NOT NULL,
    pais VARCHAR(50) NOT NULL
);

CREATE TABLE aviones (
    id_avion INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    modelo VARCHAR(50) NOT NULL,
    capacidad_pasajeros INT NOT NULL,
    id_aerolinea INT NOT NULL,
    CONSTRAINT fk_avion_aerolinea FOREIGN KEY (id_aerolinea) REFERENCES aerolineas(id_aerolinea) ON DELETE CASCADE
);

CREATE TABLE vuelos (
    id_vuelo INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_vuelo VARCHAR(15) UNIQUE NOT NULL,
    id_aerolinea INT NOT NULL,
    id_origen INT NOT NULL,
    id_destino INT NOT NULL,
    id_avion INT NOT NULL,
    fecha_salida TIMESTAMP NOT NULL,
    fecha_llegada TIMESTAMP NOT NULL,
    estado VARCHAR(20) DEFAULT 'Programado' CHECK (estado IN ('Programado', 'En Vuelo', 'Aterrizado', 'Retrasado', 'Cancelado')),
    precio_base DECIMAL(10,2) NOT NULL,
    CONSTRAINT fk_vuelo_aerolinea FOREIGN KEY (id_aerolinea) REFERENCES aerolineas(id_aerolinea),
    CONSTRAINT fk_vuelo_origen FOREIGN KEY (id_origen) REFERENCES aeropuertos(id_aeropuerto),
    CONSTRAINT fk_vuelo_destino FOREIGN KEY (id_destino) REFERENCES aeropuertos(id_aeropuerto),
    CONSTRAINT fk_vuelo_avion FOREIGN KEY (id_avion) REFERENCES aviones(id_avion)
);

CREATE TABLE reservas (
    id_reserva INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pasajero INT NOT NULL,
    id_vuelo INT NOT NULL,
    fecha_reserva TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    asiento VARCHAR(5) NOT NULL,
    clase VARCHAR(20) DEFAULT 'Turista' CHECK (clase IN ('Turista', 'Business', 'Primera')),
    precio_final DECIMAL(10,2) NOT NULL,
    CONSTRAINT fk_reserva_pasajero FOREIGN KEY (id_pasajero) REFERENCES pasajeros(id_pasajero),
    CONSTRAINT fk_reserva_vuelo FOREIGN KEY (id_vuelo) REFERENCES vuelos(id_vuelo)
);

CREATE TABLE equipaje (
    id_equipaje INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_reserva INT NOT NULL,
    peso_kg DECIMAL(5,2) NOT NULL,
    tipo VARCHAR(20) DEFAULT 'Bodega' CHECK (tipo IN ('Mano', 'Bodega')),
    CONSTRAINT fk_equipaje_reserva FOREIGN KEY (id_reserva) REFERENCES reservas(id_reserva) ON DELETE CASCADE
);

-- 3. CARGA DE DATOS (DML)
-- -----------------------------------------------------------------------------
BEGIN;

-- AEROLÍNEAS
INSERT INTO aerolineas (nombre, codigo_iata, pais_origen) VALUES 
('Iberia', 'IBE', 'España'), ('Emirates', 'UAE', 'Emiratos Árabes'), ('Lufthansa', 'DLH', 'Alemania'),
('Delta Air Lines', 'DAL', 'USA'), ('Ryanair', 'RYR', 'Irlanda'), ('Air France', 'AFR', 'Francia'),
('Qatar Airways', 'QTR', 'Qatar'), ('LATAM', 'LAN', 'Chile'), ('Japan Airlines', 'JAL', 'Japón'),
('British Airways', 'BAW', 'Reino Unido'), ('Aeroméxico', 'AMX', 'México'), ('Turkish Airlines', 'THY', 'Turquía'),
('Vueling', 'VLG', 'España'), ('KLM', 'KLM', 'Países Bajos'), ('TAP Air Portugal', 'TAP', 'Portugal'),
('Alitalia', 'AZA', 'Italia'), ('Swiss Air', 'SWR', 'Suiza'), ('United Airlines', 'UAL', 'USA'),
('Copa Airlines', 'CMP', 'Panamá'), ('Avianca', 'AVA', 'Colombia');

-- Generamos filiales para llegar a 100
INSERT INTO aerolineas (nombre, codigo_iata, pais_origen)
SELECT nombre || ' Express', LEFT(codigo_iata, 2) || id_aerolinea, pais_origen 
FROM aerolineas WHERE id_aerolinea <= 80;

-- AEROPUERTOS
INSERT INTO aeropuertos (nombre, codigo_iata, ciudad, pais) VALUES 
('Adolfo Suárez Madrid-Barajas', 'MAD', 'Madrid', 'España'), ('John F. Kennedy', 'JFK', 'Nueva York', 'USA'),
('Narita', 'NRT', 'Tokio', 'Japón'), ('Heathrow', 'LHR', 'Londres', 'Reino Unido'),
('Charles de Gaulle', 'CDG', 'París', 'Francia'), ('Dubai International', 'DXB', 'Dubai', 'EAU'),
('El Dorado', 'BOG', 'Bogotá', 'Colombia'), ('Benito Juárez', 'MEX', 'Ciudad de México', 'México'),
('Frankfurt Airport', 'FRA', 'Frankfurt', 'Alemania'), ('Sydney Airport', 'SYD', 'Sydney', 'Australia'),
('El Prat', 'BCN', 'Barcelona', 'España'), ('Ezeiza', 'EZE', 'Buenos Aires', 'Argentina'),
('Haneda', 'HND', 'Tokio', 'Japón'), ('Fiumicino', 'FCO', 'Roma', 'Italia'),
('Changi', 'SIN', 'Singapur', 'Singapur');

-- Multiplicamos aeropuertos
INSERT INTO aeropuertos (nombre, codigo_iata, ciudad, pais)
SELECT 'Aeropuerto Regional ' || id_aeropuerto, 'A' || id_aeropuerto, 'Ciudad Extra', pais 
FROM aeropuertos LIMIT 130;

-- AVIONES
INSERT INTO aviones (modelo, capacidad_pasajeros, id_aerolinea)
SELECT 
    CASE (id_aerolinea % 4)
        WHEN 0 THEN 'Boeing 737'
        WHEN 1 THEN 'Airbus A320'
        WHEN 2 THEN 'Boeing 787 Dreamliner'
        ELSE 'Airbus A350'
    END,
    CASE (id_aerolinea % 4)
        WHEN 0 THEN 180 WHEN 1 THEN 160 WHEN 2 THEN 250 ELSE 350 END,
    id_aerolinea
FROM aerolineas;

-- PASAJEROS (+1000 registros mediante duplicación lógica)
INSERT INTO pasajeros (nombre, apellidos, pasaporte, nacionalidad, email, telefono) VALUES 
('Juan', 'García', 'PAS0001', 'España', 'juan@mail.com', '600000001'),
('Ana', 'Martínez', 'PAS0002', 'México', 'ana@mail.com', '555000002'),
('John', 'Doe', 'PAS0003', 'USA', 'john@mail.com', '101000003'),
('Li', 'Wei', 'PAS0004', 'China', 'li@mail.com', '808000004'),
('Maria', 'Rossi', 'PAS0005', 'Italia', 'maria@mail.com', '303000005');

-- Multiplicación de pasajeros
INSERT INTO pasajeros (nombre, apellidos, pasaporte, nacionalidad, email, telefono)
SELECT nombre || 'x', apellidos || id_pasajero, 'P' || (id_pasajero + 10), nacionalidad, id_pasajero || email, telefono FROM pasajeros;
INSERT INTO pasajeros (nombre, apellidos, pasaporte, nacionalidad, email, telefono)
SELECT nombre || 'y', apellidos || id_pasajero, 'P' || (id_pasajero + 200), nacionalidad, id_pasajero || 'a' || email, telefono FROM pasajeros;
INSERT INTO pasajeros (nombre, apellidos, pasaporte, nacionalidad, email, telefono)
SELECT nombre || 'z', apellidos || id_pasajero, 'P' || (id_pasajero + 1000), nacionalidad, id_pasajero || 'b' || email, telefono FROM pasajeros;

-- VUELOS
INSERT INTO vuelos (numero_vuelo, id_aerolinea, id_origen, id_destino, id_avion, fecha_salida, fecha_llegada, estado, precio_base)
SELECT 
    'FL' || id_avion || '-' || id_aerolinea,
    id_aerolinea,
    (id_avion % 20) + 1,
    (id_avion % 20) + 2,
    id_avion,
    '2024-01-01 08:00:00'::timestamp + (id_avion * interval '1 hour'),
    '2024-01-01 12:00:00'::timestamp + (id_avion * interval '1 hour'),
    'Aterrizado',
    150.00 + (id_avion * 2)
FROM aviones;

-- Vuelos futuros
INSERT INTO vuelos (numero_vuelo, id_aerolinea, id_origen, id_destino, id_avion, fecha_salida, fecha_llegada, estado, precio_base)
SELECT 
    'FL-P-' || id_vuelo,
    id_aerolinea, id_origen, id_destino, id_avion,
    fecha_salida + interval '1 month',
    fecha_llegada + interval '1 month',
    'Programado',
    precio_base * 1.2
FROM vuelos LIMIT 300;

-- RESERVAS (Cruzado masivo)
INSERT INTO reservas (id_pasajero, id_vuelo, asiento, clase, precio_final)
SELECT 
    p.id_pasajero,
    v.id_vuelo,
    floor(random() * 30 + 1)::text || 'B',
    CASE WHEN p.id_pasajero % 10 = 0 THEN 'Business' ELSE 'Turista' END,
    v.precio_base + 20
FROM pasajeros p
JOIN vuelos v ON (p.id_pasajero % 50) = (v.id_vuelo % 50)
LIMIT 2500;

-- EQUIPAJE
INSERT INTO equipaje (id_reserva, peso_kg, tipo)
SELECT id_reserva, 7.5, 'Mano' FROM reservas;

INSERT INTO equipaje (id_reserva, peso_kg, tipo)
SELECT id_reserva, 21.0, 'Bodega' FROM reservas WHERE id_reserva % 3 = 0;

COMMIT;

-- 4. CONSULTA DE COMPROBACIÓN
-- -----------------------------------------------------------------------------
SELECT 'Aerolíneas' as Tabla, COUNT(*) as Total FROM aerolineas
UNION ALL SELECT 'Aeropuertos', COUNT(*) FROM aeropuertos
UNION ALL SELECT 'Pasajeros', COUNT(*) FROM pasajeros
UNION ALL SELECT 'Aviones', COUNT(*) FROM aviones
UNION ALL SELECT 'Vuelos', COUNT(*) FROM vuelos
UNION ALL SELECT 'Reservas', COUNT(*) FROM reservas
UNION ALL SELECT 'Equipaje', COUNT(*) FROM equipaje;