-- =============================================================================
-- SCRIPT SQL: SISTEMA DE GESTIÓN HOTELERA
-- PostgreSQL 12+
-- Autor: Efrén Sánchez / Optimización de datos: IA
-- =============================================================================

-- 1. LIMPIEZA DE ESTRUCTURAS
-- -----------------------------------------------------------------------------
DROP TABLE IF EXISTS consumos_extras CASCADE;
DROP TABLE IF EXISTS servicios CASCADE;
DROP TABLE IF EXISTS reservas CASCADE;
DROP TABLE IF EXISTS habitaciones CASCADE;
DROP TABLE IF EXISTS tipos_habitacion CASCADE;
DROP TABLE IF EXISTS huespedes CASCADE;

DROP TYPE IF EXISTS estado_hab;
DROP TYPE IF EXISTS estado_res;

-- 2. DEFINICIÓN DE TIPOS PERSONALIZADOS (ENUMS)
-- -----------------------------------------------------------------------------
CREATE TYPE estado_hab AS ENUM ('Disponible', 'Ocupada', 'Limpieza', 'Mantenimiento');
CREATE TYPE estado_res AS ENUM ('Confirmada', 'Pendiente', 'Cancelada', 'Finalizada');

-- 3. DEFINICIÓN DEL ESQUEMA (DDL)
-- -----------------------------------------------------------------------------

CREATE TABLE tipos_habitacion (
    id_tipo INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    precio_noche NUMERIC(10,2) NOT NULL,
    capacidad_personas SMALLINT NOT NULL,
    descripcion TEXT
);

CREATE TABLE habitaciones (
    id_habitacion INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero VARCHAR(10) UNIQUE NOT NULL,
    id_tipo INT NOT NULL,
    piso SMALLINT NOT NULL,
    estado estado_hab DEFAULT 'Disponible',
    CONSTRAINT fk_hab_tipo FOREIGN KEY (id_tipo) REFERENCES tipos_habitacion(id_tipo)
);

CREATE TABLE huespedes (
    id_huesped INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    apellidos VARCHAR(100) NOT NULL,
    documento_id VARCHAR(20) UNIQUE NOT NULL,
    email VARCHAR(100),
    telefono VARCHAR(20),
    pais VARCHAR(50)
);

CREATE TABLE reservas (
    id_reserva INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_huesped INT NOT NULL,
    id_habitacion INT NOT NULL,
    fecha_reserva TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fecha_entrada DATE NOT NULL,
    fecha_salida DATE NOT NULL,
    estado_reserva estado_res DEFAULT 'Pendiente',
    total_alojamiento NUMERIC(10,2) DEFAULT 0.00,
    CONSTRAINT fk_res_huesped FOREIGN KEY (id_huesped) REFERENCES huespedes(id_huesped),
    CONSTRAINT fk_res_hab FOREIGN KEY (id_habitacion) REFERENCES habitaciones(id_habitacion),
    CONSTRAINT chk_fechas CHECK (fecha_salida > fecha_entrada)
);

CREATE TABLE servicios (
    id_servicio INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    precio NUMERIC(10,2) NOT NULL
);

CREATE TABLE consumos_extras (
    id_consumo INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_reserva INT NOT NULL,
    id_servicio INT NOT NULL,
    fecha_consumo TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    cantidad SMALLINT DEFAULT 1,
    subtotal NUMERIC(10,2) NOT NULL,
    CONSTRAINT fk_cons_reserva FOREIGN KEY (id_reserva) REFERENCES reservas(id_reserva),
    CONSTRAINT fk_cons_servicio FOREIGN KEY (id_servicio) REFERENCES servicios(id_servicio)
);

-- 4. CARGA DE DATOS (DML)
-- -----------------------------------------------------------------------------
BEGIN;

-- Tipos de habitación
INSERT INTO tipos_habitacion (nombre, precio_noche, capacidad_personas, descripcion) VALUES
('Económica Single', 35.00, 1, 'Habitación sencilla para viajeros individuales.'),
('Estándar Doble', 65.00, 2, 'Habitación con dos camas o matrimonial.'),
('Junior Suite', 110.00, 2, 'Suite con sala de estar y minibar.'),
('Familiar Deluxe', 150.00, 4, 'Habitación amplia para familias de 4 personas.'),
('Suite Presidencial', 300.00, 2, 'Lujo total, jacuzzi y vista panorámica.');

-- Habitaciones (30 habitaciones automáticas)
INSERT INTO habitaciones (numero, id_tipo, piso, estado)
SELECT 
    (floor(n/6.1)+1)::text || '0' || (mod(n, 6)+1)::text, -- Genera números como 101, 102, 201...
    (mod(n, 5) + 1), -- Repite tipos del 1 al 5
    (floor(n/6.1)+1), -- Piso basado en el número
    'Disponible'
FROM generate_series(0, 29) n;

-- Servicios
INSERT INTO servicios (nombre, precio) VALUES
('Desayuno Buffet', 15.00), ('Lavandería', 12.50), ('Spa Day', 40.00), 
('Minibar Premium', 25.00), ('Parking', 10.00), ('Room Service', 18.00);

-- Huéspedes (100 registros con datos aleatorios realistas)
INSERT INTO huespedes (nombre, apellidos, documento_id, email, pais)
SELECT 
    (ARRAY['Juan', 'Maria', 'Carlos', 'Ana', 'Luis', 'Elena', 'Diego', 'Sofia', 'Mark', 'Chloe'])[floor(random() * 10 + 1)],
    (ARRAY['García', 'Rodríguez', 'Smith', 'Müller', 'Sánchez', 'Ferrari', 'Dubois', 'Gómez', 'Wilson', 'Pérez'])[floor(random() * 10 + 1)],
    'DOC-' || (1000 + n),
    'user' || n || '@example.com',
    (ARRAY['España', 'México', 'Argentina', 'Colombia', 'USA', 'Francia', 'Italia', 'Alemania'])[floor(random() * 8 + 1)]
FROM generate_series(1, 100) n;

-- Reservas (150 registros)
INSERT INTO reservas (id_huesped, id_habitacion, fecha_entrada, fecha_salida, estado_reserva, total_alojamiento)
SELECT 
    floor(random() * 99 + 1), -- ID Huésped aleatorio
    floor(random() * 29 + 1), -- ID Habitación aleatoria
    CURRENT_DATE + (n || ' days')::interval - (random() * 30 || ' days')::interval, -- Fechas variadas
    CURRENT_DATE + (n + 3 || ' days')::interval,
    (ARRAY['Confirmada', 'Pendiente', 'Cancelada', 'Finalizada'::estado_res])[floor(random() * 4 + 1)],
    (random() * 500 + 100) -- Total aleatorio aproximado
FROM generate_series(1, 150) n;

-- Consumos Extras (200 registros)
INSERT INTO consumos_extras (id_reserva, id_servicio, cantidad, subtotal)
SELECT 
    floor(random() * 149 + 1), -- Reserva aleatoria
    floor(random() * 5 + 1),   -- Servicio aleatorio
    floor(random() * 3 + 1),   -- Cantidad entre 1 y 3
    0 -- Temporalmente 0, ahora lo actualizamos
FROM generate_series(1, 200) n;

-- Actualizar los subtotales de consumos basados en el precio real del servicio
UPDATE consumos_extras ce
SET subtotal = ce.cantidad * s.precio
FROM servicios s
WHERE ce.id_servicio = s.id_servicio;

COMMIT;

-- 5. CONSULTAS DE PRUEBA
-- -----------------------------------------------------------------------------

-- A. Resumen de cuenta del cliente (Alojamiento + Extras)
SELECT 
    r.id_reserva,
    h.nombre || ' ' || h.apellidos AS cliente,
    r.total_alojamiento AS base_habitacion,
    COALESCE(SUM(ce.subtotal), 0) AS total_servicios,
    r.total_alojamiento + COALESCE(SUM(ce.subtotal), 0) AS factura_total
FROM reservas r
JOIN huespedes h ON r.id_huesped = h.id_huesped
LEFT JOIN consumos_extras ce ON r.id_reserva = ce.id_reserva
GROUP BY r.id_reserva, h.nombre, h.apellidos
LIMIT 10;

-- B. Ingresos por país (Solo reservas Finalizadas)
SELECT 
    h.pais, 
    COUNT(r.id_reserva) as num_reservas,
    SUM(r.total_alojamiento) as ingresos_hospedaje
FROM huespedes h
JOIN reservas r ON h.id_huesped = r.id_huesped
WHERE r.estado_reserva = 'Finalizada'
GROUP BY h.pais
ORDER BY ingresos_hospedaje DESC;

-- C. Servicios más populares
SELECT s.nombre, COUNT(ce.id_consumo) as veces_solicitado
FROM servicios s
LEFT JOIN consumos_extras ce ON s.id_servicio = ce.id_servicio
GROUP BY s.id_servicio
ORDER BY veces_solicitado DESC;