-- =============================================================================
-- SISTEMA DE GESTIÓN AEROPORTUARIA 
-- Volumen: +1000 Pasajeros, +600 Vuelos, +2000 Reservas
-- Oracle XE
-- Autor: Efrén Sánchez / Adaptación: IA
-- =============================================================================

-- 1. LIMPIEZA DE TABLAS (PL/SQL para evitar errores de restricción)
-- -----------------------------------------------------------------------------
BEGIN
   FOR r IN (SELECT table_name FROM user_tables WHERE table_name IN 
     ('EQUIPAJE', 'RESERVAS', 'VUELOS', 'AVIONES', 'AEROPUERTOS', 'AEROLINEAS', 'PASAJEROS'))
   LOOP
      EXECUTE IMMEDIATE 'DROP TABLE ' || r.table_name || ' CASCADE CONSTRAINTS';
   END LOOP;
END;
/

-- 2. ESTRUCTURA (DDL)
-- -----------------------------------------------------------------------------

CREATE TABLE pasajeros (
    id_pasajero NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL,
    apellidos VARCHAR2(100) NOT NULL,
    pasaporte VARCHAR2(20) UNIQUE NOT NULL,
    nacionalidad VARCHAR2(50),
    email VARCHAR2(100) UNIQUE,
    telefono VARCHAR2(20)
);

CREATE TABLE aerolineas (
    id_aerolinea NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    codigo_iata VARCHAR2(3) UNIQUE NOT NULL,
    pais_origen VARCHAR2(50)
);

CREATE TABLE aeropuertos (
    id_aeropuerto NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    codigo_iata VARCHAR2(5) UNIQUE NOT NULL,
    ciudad VARCHAR2(50) NOT NULL,
    pais VARCHAR2(50) NOT NULL
);

CREATE TABLE aviones (
    id_avion NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    modelo VARCHAR2(50) NOT NULL,
    capacidad_pasajeros NUMBER NOT NULL,
    id_aerolinea NUMBER NOT NULL,
    CONSTRAINT fk_avion_aerolinea FOREIGN KEY (id_aerolinea) REFERENCES aerolineas(id_aerolinea)
);

CREATE TABLE vuelos (
    id_vuelo NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_vuelo VARCHAR2(15) UNIQUE NOT NULL,
    id_aerolinea NUMBER NOT NULL,
    id_origen NUMBER NOT NULL,
    id_destino NUMBER NOT NULL,
    id_avion NUMBER NOT NULL,
    fecha_salida DATE NOT NULL,
    fecha_llegada DATE NOT NULL,
    estado VARCHAR2(20) DEFAULT 'Programado',
    precio_base NUMBER(10,2) NOT NULL,
    CONSTRAINT chk_estado_vuelo CHECK (estado IN ('Programado', 'En Vuelo', 'Aterrizado', 'Retrasado', 'Cancelado')),
    CONSTRAINT fk_vuelo_aerolinea FOREIGN KEY (id_aerolinea) REFERENCES aerolineas(id_aerolinea),
    CONSTRAINT fk_vuelo_origen FOREIGN KEY (id_origen) REFERENCES aeropuertos(id_aeropuerto),
    CONSTRAINT fk_vuelo_destino FOREIGN KEY (id_destino) REFERENCES aeropuertos(id_aeropuerto),
    CONSTRAINT fk_vuelo_avion FOREIGN KEY (id_avion) REFERENCES aviones(id_avion)
);

CREATE TABLE reservas (
    id_reserva NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pasajero NUMBER NOT NULL,
    id_vuelo NUMBER NOT NULL,
    fecha_reserva TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    asiento VARCHAR2(5) NOT NULL,
    clase VARCHAR2(20) DEFAULT 'Turista',
    precio_final NUMBER(10,2) NOT NULL,
    CONSTRAINT chk_clase_reserva CHECK (clase IN ('Turista', 'Business', 'Primera')),
    CONSTRAINT fk_reserva_pasajero FOREIGN KEY (id_pasajero) REFERENCES pasajeros(id_pasajero),
    CONSTRAINT fk_reserva_vuelo FOREIGN KEY (id_vuelo) REFERENCES vuelos(id_vuelo)
);

CREATE TABLE equipaje (
    id_equipaje NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_reserva NUMBER NOT NULL,
    peso_kg NUMBER(5,2) NOT NULL,
    tipo VARCHAR2(20) DEFAULT 'Bodega',
    CONSTRAINT chk_tipo_equipaje CHECK (tipo IN ('Mano', 'Bodega')),
    CONSTRAINT fk_equipaje_reserva FOREIGN KEY (id_reserva) REFERENCES reservas(id_reserva) ON DELETE CASCADE
);

-- 3. CARGA DE DATOS (DML)
-- -----------------------------------------------------------------------------

-- AEROLÍNEAS
INSERT INTO aerolineas (nombre, codigo_iata, pais_origen) VALUES ('Iberia', 'IBE', 'España');
INSERT INTO aerolineas (nombre, codigo_iata, pais_origen) VALUES ('Emirates', 'UAE', 'Emiratos Árabes');
INSERT INTO aerolineas (nombre, codigo_iata, pais_origen) VALUES ('Lufthansa', 'DLH', 'Alemania');
INSERT INTO aerolineas (nombre, codigo_iata, pais_origen) VALUES ('Delta Air Lines', 'DAL', 'USA');
INSERT INTO aerolineas (nombre, codigo_iata, pais_origen) VALUES ('Ryanair', 'RYR', 'Irlanda');
INSERT INTO aerolineas (nombre, codigo_iata, pais_origen) VALUES ('Air France', 'AFR', 'Francia');
INSERT INTO aerolineas (nombre, codigo_iata, pais_origen) VALUES ('Qatar Airways', 'QTR', 'Qatar');
INSERT INTO aerolineas (nombre, codigo_iata, pais_origen) VALUES ('LATAM', 'LAN', 'Chile');
INSERT INTO aerolineas (nombre, codigo_iata, pais_origen) VALUES ('Japan Airlines', 'JAL', 'Japón');
INSERT INTO aerolineas (nombre, codigo_iata, pais_origen) VALUES ('British Airways', 'BAW', 'Reino Unido');
INSERT INTO aerolineas (nombre, codigo_iata, pais_origen) VALUES ('Aeroméxico', 'AMX', 'México');
INSERT INTO aerolineas (nombre, codigo_iata, pais_origen) VALUES ('Turkish Airlines', 'THY', 'Turquía');
INSERT INTO aerolineas (nombre, codigo_iata, pais_origen) VALUES ('Vueling', 'VLG', 'España');
INSERT INTO aerolineas (nombre, codigo_iata, pais_origen) VALUES ('KLM', 'KLM', 'Países Bajos');
INSERT INTO aerolineas (nombre, codigo_iata, pais_origen) VALUES ('TAP Air Portugal', 'TAP', 'Portugal');
INSERT INTO aerolineas (nombre, codigo_iata, pais_origen) VALUES ('Alitalia', 'AZA', 'Italia');
INSERT INTO aerolineas (nombre, codigo_iata, pais_origen) VALUES ('Swiss Air', 'SWR', 'Suiza');
INSERT INTO aerolineas (nombre, codigo_iata, pais_origen) VALUES ('United Airlines', 'UAL', 'USA');
INSERT INTO aerolineas (nombre, codigo_iata, pais_origen) VALUES ('Copa Airlines', 'CMP', 'Panamá');
INSERT INTO aerolineas (nombre, codigo_iata, pais_origen) VALUES ('Avianca', 'AVA', 'Colombia');

-- Generamos filiales
INSERT INTO aerolineas (nombre, codigo_iata, pais_origen)
SELECT nombre || ' Express', SUBSTR(codigo_iata,1,2) || id_aerolinea, pais_origen 
FROM aerolineas WHERE id_aerolinea <= 80;

-- AEROPUERTOS
INSERT INTO aeropuertos (nombre, codigo_iata, ciudad, pais) VALUES ('Adolfo Suárez Madrid-Barajas', 'MAD', 'Madrid', 'España');
INSERT INTO aeropuertos (nombre, codigo_iata, ciudad, pais) VALUES ('John F. Kennedy', 'JFK', 'Nueva York', 'USA');
INSERT INTO aeropuertos (nombre, codigo_iata, ciudad, pais) VALUES ('Narita', 'NRT', 'Tokio', 'Japón');
INSERT INTO aeropuertos (nombre, codigo_iata, ciudad, pais) VALUES ('Heathrow', 'LHR', 'Londres', 'Reino Unido');
INSERT INTO aeropuertos (nombre, codigo_iata, ciudad, pais) VALUES ('Charles de Gaulle', 'CDG', 'París', 'Francia');
INSERT INTO aeropuertos (nombre, codigo_iata, ciudad, pais) VALUES ('Dubai International', 'DXB', 'Dubai', 'EAU');
INSERT INTO aeropuertos (nombre, codigo_iata, ciudad, pais) VALUES ('El Dorado', 'BOG', 'Bogotá', 'Colombia');
INSERT INTO aeropuertos (nombre, codigo_iata, ciudad, pais) VALUES ('Benito Juárez', 'MEX', 'Ciudad de México', 'México');
INSERT INTO aeropuertos (nombre, codigo_iata, ciudad, pais) VALUES ('Frankfurt Airport', 'FRA', 'Frankfurt', 'Alemania');
INSERT INTO aeropuertos (nombre, codigo_iata, ciudad, pais) VALUES ('Sydney Airport', 'SYD', 'Sydney', 'Australia');
INSERT INTO aeropuertos (nombre, codigo_iata, ciudad, pais) VALUES ('El Prat', 'BCN', 'Barcelona', 'España');
INSERT INTO aeropuertos (nombre, codigo_iata, ciudad, pais) VALUES ('Ezeiza', 'EZE', 'Buenos Aires', 'Argentina');
INSERT INTO aeropuertos (nombre, codigo_iata, ciudad, pais) VALUES ('Haneda', 'HND', 'Tokio', 'Japón');
INSERT INTO aeropuertos (nombre, codigo_iata, ciudad, pais) VALUES ('Fiumicino', 'FCO', 'Roma', 'Italia');
INSERT INTO aeropuertos (nombre, codigo_iata, ciudad, pais) VALUES ('Changi', 'SIN', 'Singapur', 'Singapur');

-- Multiplicamos aeropuertos
INSERT INTO aeropuertos (nombre, codigo_iata, ciudad, pais)
SELECT 'Aeropuerto Regional ' || id_aeropuerto, 'A' || id_aeropuerto, 'Ciudad Extra', pais 
FROM aeropuertos WHERE ROWNUM <= 130;

-- AVIONES
INSERT INTO aviones (modelo, capacidad_pasajeros, id_aerolinea)
SELECT 
    CASE MOD(id_aerolinea, 4)
        WHEN 0 THEN 'Boeing 737'
        WHEN 1 THEN 'Airbus A320'
        WHEN 2 THEN 'Boeing 787 Dreamliner'
        ELSE 'Airbus A350'
    END,
    CASE MOD(id_aerolinea, 4)
        WHEN 0 THEN 180 WHEN 1 THEN 160 WHEN 2 THEN 250 ELSE 350 END,
    id_aerolinea
FROM aerolineas;

-- PASAJEROS
INSERT INTO pasajeros (nombre, apellidos, pasaporte, nacionalidad, email, telefono) VALUES ('Juan', 'García', 'PAS0001', 'España', 'juan@mail.com', '600000001');
INSERT INTO pasajeros (nombre, apellidos, pasaporte, nacionalidad, email, telefono) VALUES ('Ana', 'Martínez', 'PAS0002', 'México', 'ana@mail.com', '555000002');
INSERT INTO pasajeros (nombre, apellidos, pasaporte, nacionalidad, email, telefono) VALUES ('John', 'Doe', 'PAS0003', 'USA', 'john@mail.com', '101000003');
INSERT INTO pasajeros (nombre, apellidos, pasaporte, nacionalidad, email, telefono) VALUES ('Li', 'Wei', 'PAS0004', 'China', 'li@mail.com', '808000004');
INSERT INTO pasajeros (nombre, apellidos, pasaporte, nacionalidad, email, telefono) VALUES ('Maria', 'Rossi', 'PAS0005', 'Italia', 'maria@mail.com', '303000005');

-- Multiplicación exponencial (Simulada para Oracle)
INSERT INTO pasajeros (nombre, apellidos, pasaporte, nacionalidad, email, telefono)
SELECT nombre || 'x', apellidos || id_pasajero, 'P' || (id_pasajero + 10), nacionalidad, id_pasajero || email, telefono FROM pasajeros;
INSERT INTO pasajeros (nombre, apellidos, pasaporte, nacionalidad, email, telefono)
SELECT nombre || 'y', apellidos || id_pasajero, 'P' || (id_pasajero + 200), nacionalidad, id_pasajero || 'a' || email, telefono FROM pasajeros;
INSERT INTO pasajeros (nombre, apellidos, pasaporte, nacionalidad, email, telefono)
SELECT nombre || 'z', apellidos || id_pasajero, 'P' || (id_pasajero + 1000), nacionalidad, id_pasajero || 'b' || email, telefono FROM pasajeros;

-- VUELOS
INSERT INTO vuelos (numero_vuelo, id_aerolinea, id_origen, id_destino, id_avion, fecha_salida, fecha_llegada, estado, precio_base)
SELECT 
    'FL' || id_avion || '-' || id_aerolinea,
    id_aerolinea,
    MOD(id_avion, 20) + 1,
    MOD(id_avion, 20) + 2,
    id_avion,
    TO_DATE('2024-01-01 08:00:00', 'YYYY-MM-DD HH24:MI:SS') + (id_avion/24),
    TO_DATE('2024-01-01 12:00:00', 'YYYY-MM-DD HH24:MI:SS') + (id_avion/24),
    'Aterrizado',
    150.00 + (id_avion * 2)
FROM aviones;

-- Vuelos futuros
INSERT INTO vuelos (numero_vuelo, id_aerolinea, id_origen, id_destino, id_avion, fecha_salida, fecha_llegada, estado, precio_base)
SELECT 
    'FL-P-' || id_vuelo,
    id_aerolinea, id_origen, id_destino, id_avion,
    ADD_MONTHS(fecha_salida, 1),
    ADD_MONTHS(fecha_llegada, 1),
    'Programado',
    precio_base * 1.2
FROM vuelos WHERE ROWNUM <= 300;

-- RESERVAS (Aprox 2500 registros)
INSERT INTO reservas (id_pasajero, id_vuelo, asiento, clase, precio_final)
SELECT 
    p.id_pasajero,
    v.id_vuelo,
    FLOOR(DBMS_RANDOM.VALUE(1, 30)) || 'B',
    CASE WHEN MOD(p.id_pasajero, 10) = 0 THEN 'Business' ELSE 'Turista' END,
    v.precio_base + 20
FROM pasajeros p
JOIN vuelos v ON MOD(p.id_pasajero, 50) = MOD(v.id_vuelo, 50)
WHERE ROWNUM <= 2500;

-- EQUIPAJE
INSERT INTO equipaje (id_reserva, peso_kg, tipo)
SELECT id_reserva, 7.5, 'Mano' FROM reservas;

INSERT INTO equipaje (id_reserva, peso_kg, tipo)
SELECT id_reserva, 21.0, 'Bodega' FROM reservas WHERE MOD(id_reserva, 3) = 0;

COMMIT;

-- 4. COMPROBACIÓN
-- -----------------------------------------------------------------------------
SELECT 'Aerolineas' as Tabla, COUNT(*) as Total FROM aerolineas
UNION ALL SELECT 'Aeropuertos', COUNT(*) FROM aeropuertos
UNION ALL SELECT 'Pasajeros', COUNT(*) FROM pasajeros
UNION ALL SELECT 'Aviones', COUNT(*) FROM aviones
UNION ALL SELECT 'Vuelos', COUNT(*) FROM vuelos
UNION ALL SELECT 'Reservas', COUNT(*) FROM reservas
UNION ALL SELECT 'Equipaje', COUNT(*) FROM equipaje;