-- =============================================================================
-- SCRIPT SQL INTEGRAL: SISTEMA DE GESTIÓN DE BIBLIOTECA (VERSIÓN ORACLE)
-- =============================================================================

-- En Oracle no se usa "CREATE DATABASE". Se trabaja sobre un Esquema/Usuario.
-- Asegúrate de estar conectado con un usuario con permisos suficientes.

-- 1. ELIMINACIÓN DE TABLAS (Manejo de dependencias con CASCADE CONSTRAINTS)
-- -----------------------------------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE sanciones CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE reservas CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE prestamos CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE ejemplares CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE empleados CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE usuarios CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE libros CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE generos CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE editoriales CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE autores CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

-- 2. DEFINICIÓN DEL ESQUEMA DE TABLAS (DDL)
-- -----------------------------------------------------------------------------

CREATE TABLE autores (
    id_autor    NUMBER(10) NOT NULL,
    nombre      VARCHAR2(50) NOT NULL,
    apellido1   VARCHAR2(50),
    apellido2   VARCHAR2(50),
    nacionalidad VARCHAR2(50),
    fecha_nac   DATE NOT NULL,
    fecha_dep   DATE,
    CONSTRAINT pk_autores PRIMARY KEY (id_autor)
);

CREATE TABLE editoriales (
    id_editorial NUMBER(10) NOT NULL,
    nombre       VARCHAR2(100) NOT NULL,
    direccion    VARCHAR2(150),
    telefono     VARCHAR2(20),
    email        VARCHAR2(100),
    CONSTRAINT pk_editoriales PRIMARY KEY (id_editorial)
);

CREATE TABLE generos (
    id_genero NUMBER(10) NOT NULL,
    nombre    VARCHAR2(50) NOT NULL,
    CONSTRAINT pk_generos PRIMARY KEY (id_genero)
);

CREATE TABLE libros (
    id_libro     NUMBER(10) NOT NULL,
    titulo       VARCHAR2(150) NOT NULL,
    id_autor     NUMBER(10) NOT NULL,
    id_editorial NUMBER(10) NOT NULL,
    fecha_pub    DATE NOT NULL,
    paginas      NUMBER(10) NOT NULL,
    id_genero    NUMBER(10) NOT NULL,
    isbn         VARCHAR2(20) NOT NULL,
    CONSTRAINT pk_libros PRIMARY KEY (id_libro),
    CONSTRAINT fk_libros_autor FOREIGN KEY (id_autor) REFERENCES autores(id_autor),
    CONSTRAINT fk_libros_editorial FOREIGN KEY (id_editorial) REFERENCES editoriales(id_editorial),
    CONSTRAINT fk_libros_genero FOREIGN KEY (id_genero) REFERENCES generos(id_genero)
);

CREATE TABLE usuarios (
    id_usuario NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    nombre     VARCHAR2(50) NOT NULL,
    apellidos  VARCHAR2(100) NOT NULL,
    dni        VARCHAR2(15) NOT NULL,
    email      VARCHAR2(100),
    telefono   VARCHAR2(20),
    CONSTRAINT pk_usuarios PRIMARY KEY (id_usuario),
    CONSTRAINT uk_usuarios_dni UNIQUE (dni)
);

CREATE TABLE empleados (
    id_empleado NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    nombre      VARCHAR2(50) NOT NULL,
    apellidos   VARCHAR2(100) NOT NULL,
    cargo       VARCHAR2(50),
    salario     NUMBER(10,2),
    CONSTRAINT pk_empleados PRIMARY KEY (id_empleado)
);

CREATE TABLE ejemplares (
    id_ejemplar NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    id_libro    NUMBER(10) NOT NULL,
    estado      VARCHAR2(20) DEFAULT 'Disponible',
    CONSTRAINT pk_ejemplares PRIMARY KEY (id_ejemplar),
    CONSTRAINT fk_ejemplares_libro FOREIGN KEY (id_libro) REFERENCES libros(id_libro),
    CONSTRAINT ck_estado_ejemplar CHECK (estado IN ('Disponible', 'Prestado', 'Reservado', 'Mantenimiento', 'Extraviado', 'Dañado'))
);

CREATE TABLE prestamos (
    id_prestamo             NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    id_usuario              NUMBER(10) NOT NULL,
    id_ejemplar             NUMBER(10) NOT NULL,
    fecha_inicio            DATE NOT NULL,
    fecha_devolucion_prevista DATE NOT NULL,
    fecha_devolucion_real   DATE DEFAULT NULL,
    CONSTRAINT pk_prestamos PRIMARY KEY (id_prestamo),
    CONSTRAINT fk_prestamos_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario),
    CONSTRAINT fk_prestamos_ejemplar FOREIGN KEY (id_ejemplar) REFERENCES ejemplares(id_ejemplar)
);

CREATE TABLE reservas (
    id_reserva    NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    id_usuario    NUMBER(10) NOT NULL,
    id_libro      NUMBER(10) NOT NULL,
    fecha_reserva DATE NOT NULL,
    CONSTRAINT pk_reservas PRIMARY KEY (id_reserva),
    CONSTRAINT fk_reservas_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario),
    CONSTRAINT fk_reservas_libro FOREIGN KEY (id_libro) REFERENCES libros(id_libro)
);

CREATE TABLE sanciones (
    id_sancion  NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    id_usuario  NUMBER(10) NOT NULL,
    id_prestamo NUMBER(10) NOT NULL,
    motivo      VARCHAR2(255),
    monto       NUMBER(10,2),
    pagada      NUMBER(1) DEFAULT 0, -- Oracle no tiene BOOLEAN nativo en SQL, usamos 0/1
    fecha_pago  DATE DEFAULT NULL,
    CONSTRAINT pk_sanciones PRIMARY KEY (id_sancion),
    CONSTRAINT fk_sanciones_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario),
    CONSTRAINT fk_sanciones_prestamo FOREIGN KEY (id_prestamo) REFERENCES prestamos(id_prestamo),
    CONSTRAINT ck_sanciones_pagada CHECK (pagada IN (0, 1))
);

-- 3. INSERCIÓN DE DATOS
-- -----------------------------------------------------------------------------

-- Generos
INSERT INTO generos (id_genero, nombre) VALUES (1, 'Teatro');
INSERT INTO generos (id_genero, nombre) VALUES (2, 'Narrativa clásica');
INSERT INTO generos (id_genero, nombre) VALUES (3, 'Narrativa contemporánea');
INSERT INTO generos (id_genero, nombre) VALUES (4, 'Fantasía');
INSERT INTO generos (id_genero, nombre) VALUES (5, 'Ciencia ficción');
INSERT INTO generos (id_genero, nombre) VALUES (6, 'Thriller');
INSERT INTO generos (id_genero, nombre) VALUES (7, 'Poesía');

-- Editoriales
INSERT INTO editoriales (id_editorial, nombre, direccion, telefono, email) VALUES (1, 'Editorial Planeta', 'C/ Juan Ignacio Luca de Tena 17, Madrid', '913000001', 'info@planeta.es');
INSERT INTO editoriales (id_editorial, nombre, direccion, telefono, email) VALUES (2, 'Penguin Random House', 'Travessera de Gràcia 47, Barcelona', '932000002', 'contacto@penguinrandomhouse.es');
INSERT INTO editoriales (id_editorial, nombre, direccion, telefono, email) VALUES (3, 'Alfaguara', 'C/ Torrelaguna 60, Madrid', '914000003', 'info@alfaguara.es');
INSERT INTO editoriales (id_editorial, nombre, direccion, telefono, email) VALUES (4, 'Ediciones SM', 'C/ Impresores 2, Boadilla del Monte, Madrid', '915000004', 'info@edsm.es');
INSERT INTO editoriales (id_editorial, nombre, direccion, telefono, email) VALUES (5, 'Anagrama', 'C/ Pau Claris 172, Barcelona', '933000005', 'info@anagrama-ed.es');
INSERT INTO editoriales (id_editorial, nombre, direccion, telefono, email) VALUES (6, 'Ediciones Minotauro', 'Av. Diagonal 662, Barcelona', '934000006', 'info@minotauro.es');
INSERT INTO editoriales (id_editorial, nombre, direccion, telefono, email) VALUES (7, 'Alianza Editorial', 'C/ Juan Ignacio Luca de Tena 15, Madrid', '913000007', 'contacto@alianzaeditorial.es');

-- Autores (Se usa formato de fecha ISO)
INSERT INTO autores (id_autor, nombre, apellido1, apellido2, nacionalidad, fecha_nac, fecha_dep) VALUES (1, 'Miguel', 'de Cervantes', 'Saavedra', 'España', DATE '1547-09-29', DATE '1616-04-22');
INSERT INTO autores (id_autor, nombre, apellido1, apellido2, nacionalidad, fecha_nac, fecha_dep) VALUES (2, 'Francisco', 'de Quevedo', 'y Villegas', 'España', DATE '1580-09-14', DATE '1645-09-08');
INSERT INTO autores (id_autor, nombre, apellido1, apellido2, nacionalidad, fecha_nac, fecha_dep) VALUES (3, 'Lope', 'de Vega', 'Carpio', 'España', DATE '1562-11-25', DATE '1635-08-27');
INSERT INTO autores (id_autor, nombre, apellido1, apellido2, nacionalidad, fecha_nac, fecha_dep) VALUES (11,'Arturo', 'Pérez-Reverte', NULL, 'España', DATE '1951-11-25', NULL);
INSERT INTO autores (id_autor, nombre, apellido1, apellido2, nacionalidad, fecha_nac, fecha_dep) VALUES (12,'Carlos', 'Ruiz', 'Zafón', 'España', DATE '1964-09-25', DATE '2020-06-19');
INSERT INTO autores (id_autor, nombre, apellido1, apellido2, nacionalidad, fecha_nac, fecha_dep) VALUES (18,'John Ronald Reuel', 'Tolkien', NULL, 'Reino Unido', DATE '1892-01-03', DATE '1973-09-02');
INSERT INTO autores (id_autor, nombre, apellido1, apellido2, nacionalidad, fecha_nac, fecha_dep) VALUES (42,'Liu', 'Cixin', NULL, 'China', DATE '1963-06-23', NULL);

-- Libros (Muestra representativa)
INSERT INTO libros (id_libro, titulo, id_autor, id_editorial, fecha_pub, paginas, id_genero, isbn) VALUES (1, 'Don Quijote de la Mancha', 1, 1, DATE '1605-01-16', 1056, 2, '9788491050294');
INSERT INTO libros (id_libro, titulo, id_autor, id_editorial, fecha_pub, paginas, id_genero, isbn) VALUES (69, 'La sombra del viento', 12, 3, DATE '2001-01-01', 576, 3, '9788408172173');
INSERT INTO libros (id_libro, titulo, id_autor, id_editorial, fecha_pub, paginas, id_genero, isbn) VALUES (108, 'El hobbit', 18, 6, DATE '1937-01-01', 320, 4, '9788445000683');
INSERT INTO libros (id_libro, titulo, id_autor, id_editorial, fecha_pub, paginas, id_genero, isbn) VALUES (164, 'El problema de los tres cuerpos', 42, 2, DATE '2006-01-01', 416, 5, '9780765377067');

-- Usuarios
INSERT INTO usuarios (nombre, apellidos, dni, email, telefono) VALUES ('Juan', 'García Pérez', '12345678A', 'juan.garcia@email.com', '600111222');
INSERT INTO usuarios (nombre, apellidos, dni, email, telefono) VALUES ('María', 'López Martínez', '87654321B', 'maria.lopez@email.com', '600333444');

-- Empleados
INSERT INTO empleados (nombre, apellidos, cargo, salario) VALUES ('Ana', 'Rodríguez Soler', 'Bibliotecaria Jefe', 2500.00);

-- Ejemplares
INSERT INTO ejemplares (id_libro, estado) VALUES (1, 'Disponible');
INSERT INTO ejemplares (id_libro, estado) VALUES (69, 'Prestado');
INSERT INTO ejemplares (id_libro, estado) VALUES (108, 'Disponible');

-- Prestamos
INSERT INTO prestamos (id_usuario, id_ejemplar, fecha_inicio, fecha_devolucion_prevista) VALUES (1, 2, DATE '2024-05-01', DATE '2024-05-15');

-- Sanciones (pagada es NUMBER(1): 0 o 1)
INSERT INTO sanciones (id_usuario, id_prestamo, motivo, monto, pagada) VALUES (1, 1, 'Retraso en devolución Quijote', 5.50, 0);

COMMIT;

-- =============================================================================
-- CONSULTAS DE COMPROBACIÓN (ESTILO ORACLE)
-- =============================================================================

-- 1. Ver usuarios con sanciones pendientes
SELECT u.nombre, u.apellidos, s.motivo, s.monto 
FROM usuarios u 
JOIN sanciones s ON u.id_usuario = s.id_usuario 
WHERE s.pagada = 0;

-- 2. Resumen de stock
SELECT estado, COUNT(*) AS cantidad,
       ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM ejemplares), 2) || '%' AS porcentaje
FROM ejemplares
GROUP BY estado;