-- =============================================================================
-- SISTEMA DE GESTIÓN DE ACTIVOS TECNOLÓGICOS
-- Oracle XE
-- Autor: Efrén Sánchez / Optimización de datos: IA
-- =============================================================================

-- 1. LIMPIEZA DE TABLAS (Bloque PL/SQL para evitar errores si no existen)
BEGIN
   FOR r IN (SELECT table_name FROM user_tables WHERE table_name IN (
      'MANTENIMIENTOS', 'ASIGNACIONES', 'LICENCIAS', 'HARDWARE', 
      'SOFTWARE', 'EMPLEADOS', 'CATEGORIAS', 'FABRICANTES', 'UBICACIONES'))
   LOOP
      EXECUTE IMMEDIATE 'DROP TABLE ' || r.table_name || ' CASCADE CONSTRAINTS';
   END LOOP;
END;
/

-- 2. DEFINICIÓN DEL ESQUEMA (DDL)
-- -----------------------------------------------------------------------------

CREATE TABLE ubicaciones (
    id_ubicacion NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    edificio VARCHAR2(50),
    planta NUMBER(3)
);

CREATE TABLE fabricantes (
    id_fabricante NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    pais VARCHAR2(50),
    soporte_email VARCHAR2(100)
);

CREATE TABLE categorias (
    id_categoria NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL,
    tipo VARCHAR2(10) NOT NULL,
    CONSTRAINT check_tipo_cat CHECK (tipo IN ('Hardware', 'Software'))
);

CREATE TABLE empleados (
    id_empleado NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL,
    apellidos VARCHAR2(100) NOT NULL,
    departamento VARCHAR2(50),
    email VARCHAR2(100) UNIQUE NOT NULL,
    CONSTRAINT check_dept CHECK (departamento IN ('IT', 'Ventas', 'RRHH', 'Finanzas', 'Marketing', 'Operaciones', 'Legal'))
);

CREATE TABLE software (
    id_software NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(150) NOT NULL,
    id_fabricante NUMBER(10),
    id_categoria NUMBER(10),
    version_soft VARCHAR2(20),
    CONSTRAINT fk_soft_fab FOREIGN KEY (id_fabricante) REFERENCES fabricantes(id_fabricante),
    CONSTRAINT fk_soft_cat FOREIGN KEY (id_categoria) REFERENCES categorias(id_categoria)
);

CREATE TABLE hardware (
    id_hardware NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    modelo VARCHAR2(150) NOT NULL,
    n_serie VARCHAR2(50) UNIQUE NOT NULL,
    id_fabricante NUMBER(10),
    id_categoria NUMBER(10),
    fecha_compra DATE NOT NULL,
    costo NUMBER(12,2) NOT NULL,
    estado VARCHAR2(15) DEFAULT 'Stock',
    id_ubicacion NUMBER(10),
    CONSTRAINT check_estado CHECK (estado IN ('Stock', 'Asignado', 'Reparacion', 'Retirado')),
    CONSTRAINT fk_hard_fab FOREIGN KEY (id_fabricante) REFERENCES fabricantes(id_fabricante),
    CONSTRAINT fk_hard_cat FOREIGN KEY (id_categoria) REFERENCES categorias(id_categoria),
    CONSTRAINT fk_hard_ubi FOREIGN KEY (id_ubicacion) REFERENCES ubicaciones(id_ubicacion)
);

CREATE TABLE licencias (
    id_licencia NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_software NUMBER(10) NOT NULL,
    clave_activacion VARCHAR2(255) UNIQUE,
    fecha_expira DATE,
    tipo_licencia VARCHAR2(15),
    CONSTRAINT check_tipo_lic CHECK (tipo_licencia IN ('OEM', 'Retail', 'Suscripción', 'Volumen')),
    CONSTRAINT fk_lic_soft FOREIGN KEY (id_software) REFERENCES software(id_software)
);

CREATE TABLE asignaciones (
    id_asignacion NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empleado NUMBER(10) NOT NULL,
    id_hardware NUMBER(10) NULL,
    id_licencia NUMBER(10) NULL,
    fecha_entrega DATE NOT NULL,
    fecha_devolucion DATE NULL,
    comentarios VARCHAR2(500),
    CONSTRAINT fk_asig_emp FOREIGN KEY (id_empleado) REFERENCES empleados(id_empleado),
    CONSTRAINT fk_asig_hard FOREIGN KEY (id_hardware) REFERENCES hardware(id_hardware),
    CONSTRAINT fk_asig_lic FOREIGN KEY (id_licencia) REFERENCES licencias(id_licencia)
);

CREATE TABLE mantenimientos (
    id_mantenimiento NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_hardware NUMBER(10) NOT NULL,
    fecha_servicio DATE NOT NULL,
    descripcion VARCHAR2(1000),
    costo_reparacion NUMBER(10,2) DEFAULT 0,
    tecnico VARCHAR2(100),
    CONSTRAINT fk_mante_hard FOREIGN KEY (id_hardware) REFERENCES hardware(id_hardware)
);

-- 3. CARGA DE DATOS (DML)
-- -----------------------------------------------------------------------------

-- Ubicaciones
INSERT ALL 
INTO ubicaciones (nombre, edificio, planta) VALUES ('Data Center Principal', 'Edificio A', 0)
INTO ubicaciones (nombre, edificio, planta) VALUES ('Oficina Desarrollo 1', 'Edificio B', 1)
INTO ubicaciones (nombre, edificio, planta) VALUES ('Oficina Desarrollo 2', 'Edificio B', 2)
INTO ubicaciones (nombre, edificio, planta) VALUES ('Sala de Juntas', 'Edificio A', 3)
INTO ubicaciones (nombre, edificio, planta) VALUES ('Departamento Ventas', 'Edificio C', 1)
INTO ubicaciones (nombre, edificio, planta) VALUES ('Soporte Técnico', 'Edificio B', 0)
INTO ubicaciones (nombre, edificio, planta) VALUES ('Almacén General', 'Edificio D', 0)
INTO ubicaciones (nombre, edificio, planta) VALUES ('RRHH y Legal', 'Edificio A', 2)
INTO ubicaciones (nombre, edificio, planta) VALUES ('Marketing Creative Lab', 'Edificio C', 2)
INTO ubicaciones (nombre, edificio, planta) VALUES ('Recepción', 'Edificio A', 1)
SELECT * FROM dual;

-- Fabricantes
INSERT ALL
INTO fabricantes (nombre, pais, soporte_email) VALUES ('Dell', 'USA', 'support@dell.com')
INTO fabricantes (nombre, pais, soporte_email) VALUES ('Apple', 'USA', 'enterprise@apple.com')
INTO fabricantes (nombre, pais, soporte_email) VALUES ('Microsoft', 'USA', 'license@microsoft.com')
INTO fabricantes (nombre, pais, soporte_email) VALUES ('Lenovo', 'China', 'service@lenovo.com')
INTO fabricantes (nombre, pais, soporte_email) VALUES ('HP', 'USA', 'pro_support@hp.com')
INTO fabricantes (nombre, pais, soporte_email) VALUES ('Cisco', 'USA', 'tac@cisco.com')
INTO fabricantes (nombre, pais, soporte_email) VALUES ('Adobe', 'USA', 'creative_care@adobe.com')
INTO fabricantes (nombre, pais, soporte_email) VALUES ('Samsung', 'Corea del Sur', 'b2b.support@samsung.com')
INTO fabricantes (nombre, pais, soporte_email) VALUES ('JetBrains', 'República Checa', 'sales@jetbrains.com')
INTO fabricantes (nombre, pais, soporte_email) VALUES ('Logitech', 'Suiza', 'business@logitech.com')
SELECT * FROM dual;

-- Categorías
INSERT ALL
INTO categorias (nombre, tipo) VALUES ('Laptop', 'Hardware')
INTO categorias (nombre, tipo) VALUES ('Desktop', 'Hardware')
INTO categorias (nombre, tipo) VALUES ('Servidor', 'Hardware')
INTO categorias (nombre, tipo) VALUES ('Monitor', 'Hardware')
INTO categorias (nombre, tipo) VALUES ('Periférico', 'Hardware')
INTO categorias (nombre, tipo) VALUES ('Sistema Operativo', 'Software')
INTO categorias (nombre, tipo) VALUES ('IDE Desarrollo', 'Software')
INTO categorias (nombre, tipo) VALUES ('Suite Ofimática', 'Software')
SELECT * FROM dual;

-- Empleados (Ejemplo de carga masiva manual)
BEGIN
    FOR i IN 1..50 LOOP
        INSERT INTO empleados (nombre, apellidos, departamento, email)
        VALUES (
            'Empleado_' || i, 
            'Apellido_' || i, 
            CASE MOD(i, 7) 
                WHEN 0 THEN 'IT' WHEN 1 THEN 'Ventas' WHEN 2 THEN 'RRHH' 
                WHEN 3 THEN 'Finanzas' WHEN 4 THEN 'Marketing' WHEN 5 THEN 'Operaciones' ELSE 'Legal' 
            END,
            'user' || i || '@empresa.com'
        );
    END LOOP;
END;
/

-- Software
INSERT ALL
INTO software (nombre, id_fabricante, id_categoria, version_soft) VALUES ('Windows 11 Pro', 3, 6, '23H2')
INTO software (nombre, id_fabricante, id_categoria, version_soft) VALUES ('macOS Sonoma', 2, 6, '14.0')
INTO software (nombre, id_fabricante, id_categoria, version_soft) VALUES ('Office 365 Business', 3, 8, 'v16')
INTO software (nombre, id_fabricante, id_categoria, version_soft) VALUES ('Visual Studio 2022', 3, 7, 'Enterprise')
INTO software (nombre, id_fabricante, id_categoria, version_soft) VALUES ('Adobe Creative Cloud', 7, 8, '2024')
SELECT * FROM dual;

-- Hardware (120 registros generados)
BEGIN
    FOR i IN 1..120 LOOP
        INSERT INTO hardware (modelo, n_serie, id_fabricante, id_categoria, fecha_compra, costo, estado, id_ubicacion)
        VALUES (
            'Modelo Tech-' || MOD(i, 10),
            'SN-' || (1000 + i) || '-X',
            MOD(i, 5) + 1,
            CASE WHEN i <= 80 THEN 1 ELSE 4 END, -- Laptops y Monitores
            TO_DATE('2023-01-01', 'YYYY-MM-DD') + i,
            500 + (i * 10),
            CASE WHEN MOD(i, 5) = 0 THEN 'Stock' ELSE 'Asignado' END,
            MOD(i, 10) + 1
        );
    END LOOP;
END;
/

-- Licencias (100 registros)
BEGIN
    FOR i IN 1..100 LOOP
        INSERT INTO licencias (id_software, clave_activacion, fecha_expira, tipo_licencia)
        VALUES (
            MOD(i, 5) + 1,
            'KEY-' || i || '-ABCD-XYZ',
            TO_DATE('2025-12-31', 'YYYY-MM-DD'),
            CASE MOD(i, 4) WHEN 0 THEN 'OEM' WHEN 1 THEN 'Retail' WHEN 2 THEN 'Suscripción' ELSE 'Volumen' END
        );
    END LOOP;
END;
/

-- Asignaciones (150 registros)
-- Cruza empleados con hardware y licencias
BEGIN
    FOR i IN 1..150 LOOP
        INSERT INTO asignaciones (id_empleado, id_hardware, id_licencia, fecha_entrega)
        VALUES (
            MOD(i, 50) + 1,
            CASE WHEN i <= 120 THEN i ELSE NULL END,
            CASE WHEN i <= 100 THEN i ELSE NULL END,
            TO_DATE('2024-01-01', 'YYYY-MM-DD') + MOD(i, 30)
        );
    END LOOP;
END;
/

-- Mantenimientos
INSERT INTO mantenimientos (id_hardware, fecha_servicio, descripcion, costo_reparacion, tecnico)
SELECT 
    id_hardware, 
    fecha_compra + 180, 
    'Revisión semestral preventiva y actualización de BIOS.', 
    75.00, 
    'Técnico Oracle Senior'
FROM hardware
WHERE ROWNUM <= 40;

COMMIT;

-- 4. CONSULTA DE VERIFICACIÓN
-- -----------------------------------------------------------------------------
-- Visualizar activos asignados con sus dueños y correos
SELECT e.nombre || ' ' || e.apellidos AS empleado, 
       h.modelo, 
       h.n_serie, 
       u.nombre AS ubicacion
FROM asignaciones a
JOIN empleados e ON a.id_empleado = e.id_empleado
JOIN hardware h ON a.id_hardware = h.id_hardware
JOIN ubicaciones u ON h.id_ubicacion = u.id_ubicacion
WHERE a.fecha_devolucion IS NULL;